/* Daily workflow labels. No prices or clinical renewal schedules are assumed. */
window.DailyCopy = {
  en: {
    allDogs: "All dogs",
    noDogs: "No dogs registered yet.",
    dogFormHelp: "Only the dog’s name is required. Add an owner now or later.",
    optionalOwner: "Owner (optional)",
    ownerLater: "Add later",
    newOwner: "New owner",
    ownerName: "Owner’s name",
    saveDog: "Save dog",
    invalidDog: "Enter a dog name and check the owner details.",
    dogDraftHelp: "Save before closing or reloading. Unsaved changes will be lost.",

    sampleNote: 'Sample note',
    dailyWork: 'Your daily work', dailyIntro: 'Book a stay or walk, find a document and follow this month’s bookings.',
    planning: 'Planning', monthly: 'Monthly summary', documents: 'Documents and follow-up',
    browserStorage: 'Saved only in this browser, on this device. Not synced to an account or server.',
    browserOnly: 'Saved only in this browser', calculation: 'How counts work',
    accountStorage: 'Saved on the server for the business in your signed-in account.',
    loadError: 'These records could not be loaded. Saving is blocked to protect existing records. Reload before trying again.',
    saveError: 'Not saved. Keep your entries, check your connection or browser storage, then try again. If your account changed, copy your entries before reloading.',
    staleSave: 'Not saved. These records changed in another tab. Copy your entries, reload to get the latest records, then try again.',
    storageUnavailable: 'Not saved. Safe browser storage is unavailable. Keep your entries and open this site over HTTPS or on localhost in a current browser.',
    unknown: 'Amount not specified', noDate: 'No date recorded',
    followup: 'Document follow-up', followupHelp: 'Dates you recorded: overdue or due within 30 calendar days. This is not a clinical vaccination schedule.',
    noFollowup: 'No recorded renewal is due within the next 30 days.',
    overdue: 'Recorded date passed', due: 'Due within 30 days', later: 'Later renewal', undated: 'No renewal date recorded',
    walk: 'Walk', day: 'Day care', night: 'Overnight stay',
    dog: 'Dog', client: 'Client', dogName: 'Dog’s name', newDog: 'Add a dog', service: 'Service', start: 'Start date', end: 'End date',
    newBooking: 'New booking', editBooking: 'Edit booking', saveBooking: 'Save booking', edit: 'Edit', cancel: 'Cancel',
    units: 'units', planned: 'Planned', bookings: 'bookings',
    plannedHelp: 'Planned bookings',
    noBookings: 'No saved bookings for this month.', month: 'Month', previousMonth: 'Previous month', nextMonth: 'Next month',
    dayHelp: 'Walks and day care: one unit per calendar day, including both start and end dates. Maximum 366 units.',
    nightHelp: 'Nights: one unit per night, from check-in to the day before checkout. Checkout must be after check-in. Maximum 366 nights.',
    agreementHelp: 'An existing booking keeps its agreed unit price and currency when base rates change. Extensions use that agreement. Changing the service uses the current base rate.',
    unitRate: 'Agreed unit price', agreedRate: 'Agreed unit price (optional)',
    fillUnknownRateHint: 'Leave blank if the price is unknown. You can enter it once agreed, now or later. Once recorded, the booking keeps that price; changing base rates does not update it.',
    extension: 'Stay extension', revisedTotal: 'Revised total',
    invalidDates: 'Check the date range: 1 to 366 units; checkout must follow check-in for nights.',
    invalidBooking: 'Check the dog, client, service and dates. The booking has not been saved.',
    rates: 'Base rates', ratesLink: 'Set your prices in', ratesHelp: 'Enter your actual price per walk day, day-care day or night. Leave an unknown price blank. New bookings use these rates; existing agreements stay unchanged.',
    currency: 'Currency', saveRates: 'Save rates', invalidRate: 'Enter a nonnegative price with at most two decimals, up to 1,000,000 in the selected currency. Leave unknown prices blank.',
    summaryHelp: 'Planned bookings',
    knownAmount: 'Known amount', knownSubtotal: 'Known subtotal', unknownUnits: 'units without a price',
    allocationHelp: 'Each service day belongs to its calendar month; nights belong to the check-in night. Known subtotals exclude units without a price. Currencies stay separate.',
    documentHelp: 'Save a document or proof for this dog. Record a renewal date only if you have one; no vaccination date is inferred.',
    documentLabel: 'Document label', renewal: 'Recorded renewal date (optional)', file: 'File', maximum: 'maximum',
    saveDocument: 'Save document', openDocument: 'Download document', editRenewal: 'Edit renewal date', saveDate: 'Save date',
    noDocuments: 'No documents saved for this dog.', documentError: 'The document could not be downloaded. Check your connection and try again.',
    invalidFile: 'Choose a valid PDF, JPEG or PNG file, up to 5 MiB, with a filename no longer than 180 characters.',
    chooseOwner: 'Choose an owner', clientRequired: 'Select an existing owner or enter a new owner’s name.', saved: 'Saved',
    clinicUnavailable: 'Clinic and video consultations are not available in this app.',
    profileToComplete: 'Profile to complete', breedToConfirm: 'Breed to confirm', healthToComplete: 'Add current health and medication instructions.',
    behaviourToComplete: 'Add routines, triggers and favourite rewards.', vetToComplete: 'Add the preferred vet and emergency contact.',
    energyToComplete: 'Confirm with the owner', movementToComplete: 'Set a daily movement target', enrichmentToComplete: 'Add favourite activities', sensitivitiesToComplete: 'Add sensitivities and rest needs',
  },
  fr: {
    allDogs: "Tous les chiens",
    noDogs: "Aucun chien enregistré.",
    dogFormHelp: "Seul le nom du chien est obligatoire. Ajoutez le propriétaire maintenant ou plus tard.",
    optionalOwner: "Propriétaire (facultatif)",
    ownerLater: "À renseigner plus tard",
    newOwner: "Nouveau propriétaire",
    ownerName: "Nom du propriétaire",
    saveDog: "Enregistrer le chien",
    invalidDog: "Saisissez le nom du chien et vérifiez le propriétaire.",
    dogDraftHelp: "Enregistrez avant de fermer ou de recharger : les modifications non enregistrées seront perdues.",

    sampleNote: 'Note d’exemple',
    dailyWork: 'Votre quotidien', dailyIntro: 'Préparez un séjour ou une promenade, retrouvez un document et suivez les réservations du mois.',
    planning: 'Planning', monthly: 'Récapitulatif mensuel', documents: 'Documents et suivi',
    browserStorage: 'Enregistré uniquement dans ce navigateur, sur cet appareil. Aucune synchronisation avec un compte ou un serveur.',
    browserOnly: 'Enregistrement dans ce navigateur uniquement', calculation: 'Comment sont calculés les totaux',
    accountStorage: 'Enregistré sur le serveur, pour l’activité de votre compte connecté.',
    loadError: 'Impossible de charger ces données. L’enregistrement est bloqué pour protéger les données existantes. Rechargez la page avant de réessayer.',
    saveError: 'Non enregistré. Gardez votre saisie, vérifiez la connexion ou le stockage du navigateur, puis réessayez. Si le compte a changé, copiez votre saisie avant de recharger.',
    staleSave: 'Non enregistré. Ces données ont changé dans un autre onglet. Copiez votre saisie, rechargez la page pour retrouver les dernières données, puis réessayez.',
    storageUnavailable: 'Non enregistré. Le stockage sécurisé du navigateur est indisponible. Gardez votre saisie et ouvrez ce site en HTTPS ou sur localhost dans un navigateur récent.',
    unknown: 'Montant non renseigné', noDate: 'Aucune date renseignée',
    followup: 'Suivi des documents', followupHelp: 'Dates que vous avez renseignées : dépassées ou prévues dans les 30 jours. Il ne s’agit pas d’un calendrier vaccinal médical.',
    noFollowup: 'Aucun renouvellement renseigné n’est à prévoir dans les 30 prochains jours.',
    overdue: 'Date renseignée dépassée', due: 'À prévoir sous 30 jours', later: 'Renouvellement ultérieur', undated: 'Aucune date de renouvellement',
    walk: 'Promenade', day: 'Garde de jour', night: 'Nuitée',
    dog: 'Chien', client: 'Client', dogName: 'Nom du chien', newDog: 'Ajouter un chien', service: 'Prestation', start: 'Date de début', end: 'Date de fin',
    newBooking: 'Nouvelle réservation', editBooking: 'Modifier la réservation', saveBooking: 'Enregistrer la réservation', edit: 'Modifier', cancel: 'Annuler',
    units: 'unités', planned: 'Prévu', bookings: 'réservations',
    plannedHelp: 'Réservations prévues',
    noBookings: 'Aucune réservation enregistrée pour ce mois.', month: 'Mois', previousMonth: 'Mois précédent', nextMonth: 'Mois suivant',
    dayHelp: 'Promenades et garde de jour : une unité par jour, dates de début et de fin incluses. Maximum 366 unités.',
    nightHelp: 'Nuitées : une unité par nuit, de l’arrivée à la veille du départ. Le départ doit suivre l’arrivée. Maximum 366 nuits.',
    agreementHelp: 'Une réservation existante conserve son prix unitaire et sa devise, même si les tarifs de base changent. La prolongation reprend cet accord. Changer de prestation applique le tarif de base actuel.',
    unitRate: 'Prix unitaire convenu', agreedRate: 'Prix unitaire convenu (facultatif)',
    fillUnknownRateHint: 'Laissez vide si le prix est inconnu. Vous pourrez le renseigner une fois convenu, maintenant ou plus tard. Une fois enregistré, ce prix reste celui de la réservation ; modifier les tarifs de base ne le change pas.',
    extension: 'Prolongation du séjour', revisedTotal: 'Nouveau total',
    invalidDates: 'Vérifiez les dates : de 1 à 366 unités ; pour les nuitées, le départ doit suivre l’arrivée.',
    invalidBooking: 'Vérifiez le chien, le client, la prestation et les dates. La réservation n’a pas été enregistrée.',
    rates: 'Tarifs de base', ratesLink: 'Renseignez vos prix dans', ratesHelp: 'Indiquez votre prix réel par jour de promenade, de garde de jour ou par nuitée. Laissez vide tout prix inconnu. Ces tarifs s’appliquent aux nouvelles réservations ; les accords existants sont conservés.',
    currency: 'Devise', saveRates: 'Enregistrer les tarifs', invalidRate: 'Indiquez un prix positif ou nul, avec deux décimales au maximum, jusqu’à 1 000 000 dans la devise choisie. Laissez vide tout prix inconnu.',
    summaryHelp: 'Réservations prévues',
    knownAmount: 'Montant connu', knownSubtotal: 'Sous-total connu', unknownUnits: 'unités sans prix renseigné',
    allocationHelp: 'Chaque journée est comptée dans son mois ; chaque nuit, à sa date de début. Les sous-totaux connus excluent les unités sans prix. Les devises restent séparées.',
    documentHelp: 'Enregistrez un document ou un justificatif pour ce chien. Ajoutez une date de renouvellement uniquement si vous en disposez ; aucune date vaccinale n’est déduite.',
    documentLabel: 'Nom du document', renewal: 'Date de renouvellement renseignée (facultatif)', file: 'Fichier', maximum: 'maximum',
    saveDocument: 'Enregistrer le document', openDocument: 'Télécharger le document', editRenewal: 'Modifier le renouvellement', saveDate: 'Enregistrer la date',
    noDocuments: 'Aucun document enregistré pour ce chien.', documentError: 'Impossible de télécharger le document. Vérifiez la connexion et réessayez.',
    invalidFile: 'Choisissez un PDF, JPEG ou PNG valide de 5 Mio maximum, avec un nom de fichier de 180 caractères au plus.',
    chooseOwner: 'Choisir un propriétaire', clientRequired: 'Choisissez un propriétaire enregistré ou saisissez le nom d’un nouveau propriétaire.', saved: 'Enregistré',
    clinicUnavailable: 'Les consultations en clinique et en vidéo ne sont pas disponibles dans cette application.',
    profileToComplete: 'Profil à compléter', breedToConfirm: 'Race à confirmer', healthToComplete: 'Ajoutez les consignes actuelles de santé et de traitement.',
    behaviourToComplete: 'Ajoutez les habitudes, les déclencheurs et les récompenses préférées.', vetToComplete: 'Ajoutez le vétérinaire habituel et le contact d’urgence.',
    energyToComplete: 'À confirmer avec le propriétaire', movementToComplete: 'Précisez l’activité quotidienne', enrichmentToComplete: 'Ajoutez les activités préférées', sensitivitiesToComplete: 'Ajoutez les sensibilités et les besoins de repos',
  },
  it: {
    allDogs: "Tutti i cani",
    noDogs: "Nessun cane registrato.",
    dogFormHelp: "È richiesto solo il nome del cane. Aggiungi il proprietario ora o in seguito.",
    optionalOwner: "Proprietario (facoltativo)",
    ownerLater: "Da aggiungere più tardi",
    newOwner: "Nuovo proprietario",
    ownerName: "Nome del proprietario",
    saveDog: "Salva cane",
    invalidDog: "Inserisci il nome del cane e verifica il proprietario.",
    dogDraftHelp: "Salva prima di chiudere o ricaricare: le modifiche non salvate andranno perse.",

    sampleNote: 'Nota di esempio',
    dailyWork: 'Il tuo lavoro quotidiano', dailyIntro: 'Prenota un soggiorno o una passeggiata, ritrova un documento e segui le prenotazioni del mese.',
    planning: 'Calendario', monthly: 'Riepilogo mensile', documents: 'Documenti e scadenze',
    browserStorage: 'Salvato solo in questo browser, su questo dispositivo. Nessuna sincronizzazione con un account o un server.',
    browserOnly: 'Salvataggio solo in questo browser', calculation: 'Come vengono calcolati i totali',
    accountStorage: 'Salvato sul server per l’attività dell’account con cui hai effettuato l’accesso.',
    loadError: 'Impossibile caricare questi dati. Il salvataggio è bloccato per proteggere i dati esistenti. Ricarica la pagina prima di riprovare.',
    saveError: 'Non salvato. Conserva i dati inseriti, controlla la connessione o lo spazio del browser e riprova. Se l’account è cambiato, copia i dati prima di ricaricare.',
    staleSave: 'Non salvato. Questi dati sono cambiati in un’altra scheda. Copia i dati inseriti, ricarica la pagina per ottenere quelli aggiornati e riprova.',
    storageUnavailable: 'Non salvato. Il salvataggio sicuro nel browser non è disponibile. Conserva i dati inseriti e apri questo sito tramite HTTPS o su localhost in un browser aggiornato.',
    unknown: 'Importo non indicato', noDate: 'Nessuna data registrata',
    followup: 'Scadenze dei documenti', followupHelp: 'Date che hai registrato: già trascorse o entro 30 giorni. Non è un calendario vaccinale medico.',
    noFollowup: 'Nessun rinnovo registrato è previsto entro i prossimi 30 giorni.',
    overdue: 'Data registrata trascorsa', due: 'Entro 30 giorni', later: 'Rinnovo successivo', undated: 'Nessuna data di rinnovo',
    walk: 'Passeggiata', day: 'Custodia diurna', night: 'Pernottamento',
    dog: 'Cane', client: 'Cliente', dogName: 'Nome del cane', newDog: 'Aggiungi un cane', service: 'Servizio', start: 'Data di inizio', end: 'Data di fine',
    newBooking: 'Nuova prenotazione', editBooking: 'Modifica prenotazione', saveBooking: 'Salva prenotazione', edit: 'Modifica', cancel: 'Annulla',
    units: 'unità', planned: 'Previsto', bookings: 'prenotazioni',
    plannedHelp: 'Prenotazioni previste',
    noBookings: 'Nessuna prenotazione salvata per questo mese.', month: 'Mese', previousMonth: 'Mese precedente', nextMonth: 'Mese successivo',
    dayHelp: 'Passeggiate e custodia diurna: un’unità per giorno, comprese le date di inizio e fine. Massimo 366 unità.',
    nightHelp: 'Pernottamenti: un’unità per notte, dall’arrivo al giorno prima della partenza. La partenza deve seguire l’arrivo. Massimo 366 notti.',
    agreementHelp: 'Una prenotazione esistente mantiene il prezzo unitario e la valuta concordati anche se cambiano le tariffe di base. Le estensioni usano lo stesso accordo. Cambiando servizio si applica la tariffa di base attuale.',
    unitRate: 'Prezzo unitario concordato', agreedRate: 'Prezzo unitario concordato (facoltativo)',
    fillUnknownRateHint: 'Lascia vuoto se il prezzo è sconosciuto. Potrai inserirlo quando concordato, ora o in seguito. Una volta registrato, il prezzo della prenotazione resta invariato anche se cambiano le tariffe di base.',
    extension: 'Estensione del soggiorno', revisedTotal: 'Nuovo totale',
    invalidDates: 'Controlla le date: da 1 a 366 unità; per i pernottamenti la partenza deve seguire l’arrivo.',
    invalidBooking: 'Controlla cane, cliente, servizio e date. La prenotazione non è stata salvata.',
    rates: 'Tariffe di base', ratesLink: 'Imposta i tuoi prezzi in', ratesHelp: 'Inserisci il prezzo effettivo per giorno di passeggiata, custodia diurna o notte. Lascia vuoti i prezzi sconosciuti. Le nuove prenotazioni usano queste tariffe; gli accordi esistenti restano invariati.',
    currency: 'Valuta', saveRates: 'Salva tariffe', invalidRate: 'Inserisci un prezzo non negativo con al massimo due decimali, fino a 1.000.000 nella valuta scelta. Lascia vuoti i prezzi sconosciuti.',
    summaryHelp: 'Prenotazioni previste',
    knownAmount: 'Importo noto', knownSubtotal: 'Subtotale noto', unknownUnits: 'unità senza prezzo',
    allocationHelp: 'Ogni giornata è conteggiata nel suo mese; ogni notte nella data in cui inizia. I subtotali noti escludono le unità senza prezzo. Le valute restano separate.',
    documentHelp: 'Salva un documento o un attestato per questo cane. Registra una data di rinnovo solo se disponibile; nessuna data vaccinale viene dedotta.',
    documentLabel: 'Nome del documento', renewal: 'Data di rinnovo registrata (facoltativa)', file: 'File', maximum: 'massimo',
    saveDocument: 'Salva documento', openDocument: 'Scarica documento', editRenewal: 'Modifica rinnovo', saveDate: 'Salva data',
    noDocuments: 'Nessun documento salvato per questo cane.', documentError: 'Impossibile scaricare il documento. Controlla la connessione e riprova.',
    invalidFile: 'Scegli un file PDF, JPEG o PNG valido, fino a 5 MiB, con un nome di massimo 180 caratteri.',
    chooseOwner: 'Scegli un proprietario', clientRequired: 'Scegli un proprietario registrato o inserisci il nome di un nuovo proprietario.', saved: 'Salvato',
    clinicUnavailable: 'Le visite in clinica e le videoconsulenze non sono disponibili in questa app.',
    profileToComplete: 'Profilo da completare', breedToConfirm: 'Razza da confermare', healthToComplete: 'Aggiungi le istruzioni attuali su salute e farmaci.',
    behaviourToComplete: 'Aggiungi abitudini, fattori scatenanti e ricompense preferite.', vetToComplete: 'Aggiungi il veterinario abituale e il contatto di emergenza.',
    energyToComplete: 'Da confermare con il proprietario', movementToComplete: 'Indica l’attività quotidiana', enrichmentToComplete: 'Aggiungi le attività preferite', sensitivitiesToComplete: 'Aggiungi sensibilità ed esigenze di riposo',
  },
  de: {
    allDogs: "Alle Hunde",
    noDogs: "Noch keine Hunde erfasst.",
    dogFormHelp: "Nur der Name des Hundes ist erforderlich. Die Halterangaben können später ergänzt werden.",
    optionalOwner: "Halter (optional)",
    ownerLater: "Später ergänzen",
    newOwner: "Neuer Halter",
    ownerName: "Name des Halters",
    saveDog: "Hund speichern",
    invalidDog: "Gib den Namen des Hundes ein und prüfe die Halterangaben.",
    dogDraftHelp: "Vor dem Schließen oder Neuladen speichern. Ungespeicherte Änderungen gehen verloren.",

    sampleNote: 'Beispielnotiz',
    dailyWork: 'Dein Arbeitsalltag', dailyIntro: 'Buche einen Aufenthalt oder Spaziergang, finde Dokumente und behalte die Buchungen des Monats im Blick.',
    planning: 'Planung', monthly: 'Monatsübersicht', documents: 'Dokumente und Fristen',
    browserStorage: 'Nur in diesem Browser auf diesem Gerät gespeichert. Keine Synchronisierung mit einem Konto oder Server.',
    browserOnly: 'Nur in diesem Browser gespeichert', calculation: 'So werden die Summen berechnet',
    accountStorage: 'Auf dem Server für den Betrieb deines angemeldeten Kontos gespeichert.',
    loadError: 'Diese Daten konnten nicht geladen werden. Zum Schutz bestehender Daten ist das Speichern gesperrt. Lade die Seite neu, bevor du es erneut versuchst.',
    saveError: 'Nicht gespeichert. Behalte deine Eingaben, prüfe Verbindung oder Browserspeicher und versuche es erneut. Falls das Konto gewechselt hat, kopiere die Eingaben vor dem Neuladen.',
    staleSave: 'Nicht gespeichert. Diese Daten wurden in einem anderen Tab geändert. Kopiere deine Eingaben, lade die aktuellen Daten neu und versuche es erneut.',
    storageUnavailable: 'Nicht gespeichert. Sicheres Speichern im Browser ist nicht verfügbar. Behalte deine Eingaben und öffne diese Seite über HTTPS oder auf localhost in einem aktuellen Browser.',
    unknown: 'Betrag nicht angegeben', noDate: 'Kein Datum erfasst',
    followup: 'Dokumentfristen', followupHelp: 'Von dir erfasste Termine: überschritten oder innerhalb von 30 Tagen. Dies ist kein medizinischer Impfplan.',
    noFollowup: 'Keine erfasste Erneuerung steht in den nächsten 30 Tagen an.',
    overdue: 'Erfasstes Datum überschritten', due: 'Innerhalb von 30 Tagen', later: 'Spätere Erneuerung', undated: 'Kein Erneuerungsdatum erfasst',
    walk: 'Spaziergang', day: 'Tagesbetreuung', night: 'Übernachtung',
    dog: 'Hund', client: 'Kunde', dogName: 'Name des Hundes', newDog: 'Hund hinzufügen', service: 'Leistung', start: 'Startdatum', end: 'Enddatum',
    newBooking: 'Neue Buchung', editBooking: 'Buchung bearbeiten', saveBooking: 'Buchung speichern', edit: 'Bearbeiten', cancel: 'Abbrechen',
    units: 'Einheiten', planned: 'Geplant', bookings: 'Buchungen',
    plannedHelp: 'Geplante Buchungen',
    noBookings: 'Keine gespeicherten Buchungen für diesen Monat.', month: 'Monat', previousMonth: 'Vorheriger Monat', nextMonth: 'Nächster Monat',
    dayHelp: 'Spaziergänge und Tagesbetreuung: eine Einheit pro Kalendertag, einschließlich Start- und Enddatum. Höchstens 366 Einheiten.',
    nightHelp: 'Übernachtungen: eine Einheit pro Nacht, ab Anreise bis zum Tag vor der Abreise. Die Abreise muss nach der Anreise liegen. Höchstens 366 Nächte.',
    agreementHelp: 'Bestehende Buchungen behalten ihren vereinbarten Stückpreis und ihre Währung, auch wenn sich Grundtarife ändern. Verlängerungen nutzen diese Vereinbarung. Bei einem Leistungswechsel gilt der aktuelle Grundtarif.',
    unitRate: 'Vereinbarter Preis je Einheit', agreedRate: 'Vereinbarter Preis je Einheit (optional)',
    fillUnknownRateHint: 'Bei unbekanntem Preis leer lassen. Du kannst ihn nach der Vereinbarung jetzt oder später eintragen. Einmal erfasst, bleibt der Buchungspreis erhalten; Änderungen der Grundtarife ändern ihn nicht.',
    extension: 'Aufenthalt verlängern', revisedTotal: 'Neuer Gesamtbetrag',
    invalidDates: 'Prüfe die Daten: 1 bis 366 Einheiten; bei Übernachtungen muss die Abreise nach der Anreise liegen.',
    invalidBooking: 'Prüfe Hund, Kunde, Leistung und Daten. Die Buchung wurde nicht gespeichert.',
    rates: 'Grundtarife', ratesLink: 'Trage deine Preise ein unter', ratesHelp: 'Trage deinen tatsächlichen Preis je Spaziergangstag, Betreuungstag oder Nacht ein. Unbekannte Preise bleiben leer. Neue Buchungen nutzen diese Tarife; bestehende Vereinbarungen bleiben erhalten.',
    currency: 'Währung', saveRates: 'Tarife speichern', invalidRate: 'Gib einen nicht negativen Preis mit höchstens zwei Nachkommastellen ein, bis 1.000.000 in der gewählten Währung. Unbekannte Preise bleiben leer.',
    summaryHelp: 'Geplante Buchungen',
    knownAmount: 'Bekannter Betrag', knownSubtotal: 'Bekannte Zwischensumme', unknownUnits: 'Einheiten ohne Preis',
    allocationHelp: 'Jeder Leistungstag zählt zu seinem Kalendermonat, jede Nacht zum Tag ihres Beginns. Bekannte Zwischensummen schließen Einheiten ohne Preis aus. Währungen bleiben getrennt.',
    documentHelp: 'Speichere ein Dokument oder einen Nachweis für diesen Hund. Erfasse ein Erneuerungsdatum nur, wenn es vorliegt. Es wird kein Impftermin abgeleitet.',
    documentLabel: 'Dokumentname', renewal: 'Erfasstes Erneuerungsdatum (optional)', file: 'Datei', maximum: 'maximal',
    saveDocument: 'Dokument speichern', openDocument: 'Dokument herunterladen', editRenewal: 'Erneuerungsdatum bearbeiten', saveDate: 'Datum speichern',
    noDocuments: 'Keine Dokumente für diesen Hund gespeichert.', documentError: 'Das Dokument konnte nicht heruntergeladen werden. Prüfe die Verbindung und versuche es erneut.',
    invalidFile: 'Wähle eine gültige PDF-, JPEG- oder PNG-Datei bis 5 MiB mit einem Dateinamen von höchstens 180 Zeichen.',
    chooseOwner: 'Besitzer auswählen', clientRequired: 'Wähle einen gespeicherten Besitzer oder gib den Namen eines neuen Besitzers ein.', saved: 'Gespeichert',
    clinicUnavailable: 'Kliniktermine und Videosprechstunden sind in dieser App nicht verfügbar.',
    profileToComplete: 'Profil ergänzen', breedToConfirm: 'Rasse bestätigen', healthToComplete: 'Aktuelle Hinweise zu Gesundheit und Medikamenten ergänzen.',
    behaviourToComplete: 'Gewohnheiten, Auslöser und Lieblingsbelohnungen ergänzen.', vetToComplete: 'Gewohnte Tierarztpraxis und Notfallkontakt ergänzen.',
    energyToComplete: 'Mit dem Halter klären', movementToComplete: 'Tägliche Bewegung festlegen', enrichmentToComplete: 'Lieblingsbeschäftigungen ergänzen', sensitivitiesToComplete: 'Empfindlichkeiten und Ruhebedarf ergänzen',
  },
  es: {
    allDogs: "Todos los perros",
    noDogs: "Todavía no hay perros registrados.",
    dogFormHelp: "Solo se requiere el nombre del perro. Añade el propietario ahora o más tarde.",
    optionalOwner: "Propietario (opcional)",
    ownerLater: "Añadir más tarde",
    newOwner: "Nuevo propietario",
    ownerName: "Nombre del propietario",
    saveDog: "Guardar perro",
    invalidDog: "Introduce el nombre del perro y revisa el propietario.",
    dogDraftHelp: "Guarda antes de cerrar o recargar: se perderán los cambios sin guardar.",

    sampleNote: 'Nota de ejemplo',
    dailyWork: 'Tu trabajo diario', dailyIntro: 'Reserva una estancia o un paseo, encuentra un documento y consulta las reservas del mes.',
    planning: 'Planificación', monthly: 'Resumen mensual', documents: 'Documentos y seguimiento',
    browserStorage: 'Guardado solo en este navegador, en este dispositivo. No se sincroniza con una cuenta ni con un servidor.',
    browserOnly: 'Guardado solo en este navegador', calculation: 'Cómo se calculan los totales',
    accountStorage: 'Guardado en el servidor para el negocio de la cuenta con la que has iniciado sesión.',
    loadError: 'No se han podido cargar estos datos. El guardado está bloqueado para proteger los datos existentes. Recarga la página antes de intentarlo de nuevo.',
    saveError: 'No guardado. Conserva los datos introducidos, comprueba la conexión o el almacenamiento del navegador e inténtalo de nuevo. Si la cuenta ha cambiado, copia los datos antes de recargar.',
    staleSave: 'No guardado. Estos datos han cambiado en otra pestaña. Copia los datos introducidos, recarga la página para obtener los datos actuales e inténtalo de nuevo.',
    storageUnavailable: 'No guardado. El almacenamiento seguro del navegador no está disponible. Conserva los datos introducidos y abre este sitio mediante HTTPS o en localhost en un navegador actualizado.',
    unknown: 'Importe sin indicar', noDate: 'Sin fecha registrada',
    followup: 'Seguimiento de documentos', followupHelp: 'Fechas que has registrado: pasadas o previstas en los próximos 30 días. No es un calendario médico de vacunación.',
    noFollowup: 'Ninguna renovación registrada está prevista en los próximos 30 días.',
    overdue: 'Fecha registrada pasada', due: 'En los próximos 30 días', later: 'Renovación posterior', undated: 'Sin fecha de renovación',
    walk: 'Paseo', day: 'Cuidado de día', night: 'Noche',
    dog: 'Perro', client: 'Cliente', dogName: 'Nombre del perro', newDog: 'Añadir un perro', service: 'Servicio', start: 'Fecha de inicio', end: 'Fecha de fin',
    newBooking: 'Nueva reserva', editBooking: 'Editar reserva', saveBooking: 'Guardar reserva', edit: 'Editar', cancel: 'Cancelar',
    units: 'unidades', planned: 'Previsto', bookings: 'reservas',
    plannedHelp: 'Reservas previstas',
    noBookings: 'No hay reservas guardadas para este mes.', month: 'Mes', previousMonth: 'Mes anterior', nextMonth: 'Mes siguiente',
    dayHelp: 'Paseos y cuidado de día: una unidad por día, incluidas las fechas de inicio y fin. Máximo 366 unidades.',
    nightHelp: 'Noches: una unidad por noche, desde la llegada hasta el día anterior a la salida. La salida debe ser posterior a la llegada. Máximo 366 noches.',
    agreementHelp: 'Una reserva existente conserva el precio unitario y la moneda acordados aunque cambien las tarifas base. Las ampliaciones usan ese acuerdo. Cambiar de servicio aplica la tarifa base actual.',
    unitRate: 'Precio unitario acordado', agreedRate: 'Precio unitario acordado (opcional)',
    fillUnknownRateHint: 'Déjalo en blanco si el precio es desconocido. Podrás indicarlo cuando esté acordado, ahora o más adelante. Una vez registrado, la reserva conserva ese precio; cambiar las tarifas base no lo modifica.',
    extension: 'Ampliación de estancia', revisedTotal: 'Nuevo total',
    invalidDates: 'Revisa las fechas: de 1 a 366 unidades; para las noches, la salida debe ser posterior a la llegada.',
    invalidBooking: 'Revisa el perro, el cliente, el servicio y las fechas. La reserva no se ha guardado.',
    rates: 'Tarifas base', ratesLink: 'Indica tus precios en', ratesHelp: 'Introduce tu precio real por día de paseo, cuidado de día o noche. Deja en blanco los precios desconocidos. Las nuevas reservas usan estas tarifas; los acuerdos existentes se mantienen.',
    currency: 'Moneda', saveRates: 'Guardar tarifas', invalidRate: 'Introduce un precio no negativo con un máximo de dos decimales, hasta 1.000.000 en la moneda elegida. Deja en blanco los precios desconocidos.',
    summaryHelp: 'Reservas previstas',
    knownAmount: 'Importe conocido', knownSubtotal: 'Subtotal conocido', unknownUnits: 'unidades sin precio',
    allocationHelp: 'Cada día de servicio se cuenta en su mes; cada noche, en la fecha en que empieza. Los subtotales conocidos excluyen las unidades sin precio. Las monedas se mantienen separadas.',
    documentHelp: 'Guarda un documento o justificante para este perro. Registra una fecha de renovación solo si la tienes; no se deduce ninguna fecha de vacunación.',
    documentLabel: 'Nombre del documento', renewal: 'Fecha de renovación registrada (opcional)', file: 'Archivo', maximum: 'máximo',
    saveDocument: 'Guardar documento', openDocument: 'Descargar documento', editRenewal: 'Editar renovación', saveDate: 'Guardar fecha',
    noDocuments: 'No hay documentos guardados para este perro.', documentError: 'No se ha podido descargar el documento. Comprueba la conexión e inténtalo de nuevo.',
    invalidFile: 'Elige un archivo PDF, JPEG o PNG válido de hasta 5 MiB, con un nombre de archivo de un máximo de 180 caracteres.',
    chooseOwner: 'Elegir propietario', clientRequired: 'Selecciona un propietario registrado o introduce el nombre de uno nuevo.', saved: 'Guardado',
    clinicUnavailable: 'Las consultas en clínica y por vídeo no están disponibles en esta aplicación.',
    profileToComplete: 'Perfil por completar', breedToConfirm: 'Raza por confirmar', healthToComplete: 'Añade las instrucciones actuales de salud y medicación.',
    behaviourToComplete: 'Añade rutinas, desencadenantes y recompensas favoritas.', vetToComplete: 'Añade el veterinario habitual y el contacto de emergencia.',
    energyToComplete: 'Confirmar con el propietario', movementToComplete: 'Indica la actividad diaria', enrichmentToComplete: 'Añade las actividades favoritas', sensitivitiesToComplete: 'Añade sensibilidades y necesidades de descanso',
  },
};
