/* Accounting UI copy; contributor text is never translated. */
window.FinanceCopy={
  "fr": {
    "title": "Comptabilité",
    "journal": "Journal",
    "invoices": "Factures clients",
    "expenses": "Achats et frais",
    "review": "À vérifier",
    "rates": "Réservations et tarifs",
    "sale": "Facture client",
    "purchase": "Facture fournisseur",
    "expense": "Note de frais",
    "extra": "Extra facturé",
    "newInvoice": "Nouvelle facture",
    "newExpense": "Ajouter un frais",
    "import": "Ajouter des justificatifs",
    "export": "Exporter pour le comptable",
    "exportHelp": "Classeur Excel et originaux dans un fichier ZIP. Rien n’est envoyé.",
    "empty": "Aucune écriture. Ajoutez une facture ou un justificatif.",
    "draft": "Brouillon",
    "confirmed": "Vérifié",
    "issued": "Émise",
    "cancelled": "Annulé",
    "kind": "Type",
    "number": "Numéro / référence",
    "date": "Date",
    "due": "Échéance",
    "party": "Client / fournisseur / bénéficiaire",
    "address": "Adresse du client",
    "issuer": "Votre entreprise",
    "issuerAddress": "Adresse de votre entreprise",
    "taxId": "Numéro fiscal (facultatif)",
    "currency": "Devise",
    "category": "Catégorie",
    "service": "Prestation",
    "supplies": "Fournitures",
    "food": "Alimentation",
    "transport": "Transport",
    "health": "Vétérinaire",
    "equipment": "Matériel",
    "insurance": "Assurance",
    "other": "À classer / autre",
    "description": "Libellé",
    "quantity": "Quantité",
    "unit": "Prix unitaire TTC",
    "amount": "Montant TTC",
    "vat": "Dont TVA (facultatif)",
    "note": "Note",
    "addLine": "Ajouter une ligne / un extra",
    "remove": "Retirer",
    "booking": "Ajouter une réservation enregistrée",
    "choose": "Choisir",
    "save": "Enregistrer le brouillon",
    "confirm": "Vérifier et enregistrer",
    "issue": "Émettre la facture",
    "issueHelp": "Vérifiez le numéro, les coordonnées et les montants. Après émission, ces informations restent figées. Aucun envoi automatique.",
    "unsaved": "Enregistrez avant de fermer ou de recharger : les modifications non enregistrées seront perdues.",
    "back": "Retour au journal",
    "edit": "Ouvrir / modifier",
    "saved": "Enregistré",
    "error": "Non enregistré. Vérifiez les champs, votre connexion et l’espace disponible. Si les données ont changé ailleurs, copiez votre brouillon puis rechargez.",
    "unknown": "À compléter",
    "status": "État",
    "paid": "Payé / remboursé",
    "outstanding": "Solde",
    "payment": "Enregistrer un paiement",
    "paymentHelp": "Montant réellement reçu, payé ou remboursé. Aucune opération bancaire.",
    "print": "Imprimer / enregistrer en PDF",
    "cancel": "Annuler cette écriture",
    "reason": "Motif d’annulation",
    "source": "Justificatif original",
    "raw": "Texte reconnu — à vérifier",
    "summaryHelp": "Les réservations prévues, les factures émises et les paiements sont distincts. Les brouillons ne sont pas inclus dans les totaux.",
    "income": "Facturé",
    "costs": "Achats et frais vérifiés",
    "received": "Encaissements enregistrés",
    "spent": "Décaissements enregistrés",
    "search": "Rechercher une écriture",
    "month": "Mois (facultatif)",
    "local": "Données dans ce navigateur. Exportez pour conserver une copie.",
    "account": "Données privées de votre compte.",
    "importHelp": "Photos ou PDF : 5 Mo par fichier, 10 fichiers et 20 Mo par lot. Lecture sur cet appareil, sans service externe. Chaque zone sélectionnée crée un brouillon à vérifier.",
    "files": "Choisir des photos ou PDF",
    "camera": "Prendre une photo",
    "prepare": "Préparer les documents",
    "reading": "Lecture en cours…",
    "recognize": "Lire et créer les brouillons",
    "cropHelp": "Plusieurs factures sur la photo ? Tracez une zone autour de chacune, ou ajustez ses coordonnées en %. Retirez les zones inutiles. L’original reste intact.",
    "area": "Zone",
    "addArea": "Ajouter une zone",
    "page": "Page",
    "x": "Gauche (%)",
    "y": "Haut (%)",
    "width": "Largeur (%)",
    "height": "Hauteur (%)",
    "ocrHelp": "Les propositions peuvent être inexactes. Vérifiez chaque justificatif avant de confirmer. Les champs incertains restent à compléter.",
    "fileError": "Fichier illisible, format non pris en charge ou limite dépassée. Rien n’a été enregistré.",
    "duplicate": "Ce justificatif est déjà enregistré. Ouvrez ses écritures dans le journal.",
    "ocrFailed": "Lecture automatique indisponible. Vous pouvez conserver les originaux et compléter les brouillons à la main.",
    "manualImport": "Conserver sans reconnaissance",
    "noBookings": "Aucune réservation enregistrée à ajouter.",
    "exportError": "Export incomplet : un original ou le classeur n’a pas pu être lu. Aucun fichier partiel téléchargé.",
    "allExport": "L’export contient toutes les écritures, y compris les brouillons et annulations, et tous les originaux.",
    "sourceFile": "Fichier source",
    "payments": "Paiements",
    "lines": "Lignes",
    "readme": "À lire",
    "savePayment": "Enregistrer ce paiement",
    "profile": "Coordonnées de facturation",
    "keepProfile": "Réutiliser ces coordonnées pour les prochaines factures",
    "adjustAreas": "Ajuster les zones",
    "previewFailed": "Aperçu du PDF indisponible. Conservez l’original avec un brouillon manuel, sans page ni zone supposée.",
    "pendingDraft": "Vos modifications restent ici tant que cette page reste ouverte. Reprenez-les ou abandonnez-les avant d’ouvrir une autre écriture.",
    "resumeHelp": "Revenir à l’écriture ouverte.",
    "resume": "Reprendre l’écriture",
    "discard": "Abandonner les modifications",
    "resumeImport": "Reprendre les justificatifs",
    "discardImport": "Abandonner les justificatifs sélectionnés",
    "pendingImport": "Des justificatifs attendent déjà. Conservez-les ou abandonnez-les avant d’en choisir d’autres.",
    "unavailable": "Comptabilité indisponible. Les écritures n’ont pas pu être chargées. Enregistrement et export désactivés. Réessayez ; si nécessaire, rechargez la page.",
    "retry": "Réessayer",
    "saveEditsFirst": "Enregistrez ou abandonnez les modifications de l’écriture avant d’ajouter un paiement."
  },
  "en": {
    "title": "Accounting",
    "journal": "Ledger",
    "invoices": "Customer invoices",
    "expenses": "Purchases & expenses",
    "review": "To review",
    "rates": "Bookings & rates",
    "sale": "Customer invoice",
    "purchase": "Supplier bill",
    "expense": "Expense claim",
    "extra": "Billed extra",
    "newInvoice": "New invoice",
    "newExpense": "Add expense",
    "import": "Add documents",
    "export": "Export for accountant",
    "exportHelp": "Excel workbook and originals in a ZIP file. Nothing is sent.",
    "empty": "No records yet. Add an invoice or a document.",
    "draft": "Draft",
    "confirmed": "Reviewed",
    "issued": "Issued",
    "cancelled": "Cancelled",
    "kind": "Type",
    "number": "Number / reference",
    "date": "Date",
    "due": "Due date",
    "party": "Customer / supplier / claimant",
    "address": "Customer address",
    "issuer": "Your business",
    "issuerAddress": "Business address",
    "taxId": "Tax ID (optional)",
    "currency": "Currency",
    "category": "Category",
    "service": "Service",
    "supplies": "Supplies",
    "food": "Food",
    "transport": "Transport",
    "health": "Veterinary",
    "equipment": "Equipment",
    "insurance": "Insurance",
    "other": "Unclassified / other",
    "description": "Description",
    "quantity": "Quantity",
    "unit": "Unit price, tax included",
    "amount": "Amount, tax included",
    "vat": "Included tax (optional)",
    "note": "Note",
    "addLine": "Add line / extra",
    "remove": "Remove",
    "booking": "Add saved booking",
    "choose": "Choose",
    "save": "Save draft",
    "confirm": "Review and save",
    "issue": "Issue invoice",
    "issueHelp": "Check number, details and amounts. Once issued, these details are fixed. Nothing is sent automatically.",
    "unsaved": "Save before closing or reloading: unsaved changes will be lost.",
    "back": "Back to ledger",
    "edit": "Open / edit",
    "saved": "Saved",
    "error": "Not saved. Check fields, connection and storage. If records changed elsewhere, copy your draft then reload.",
    "unknown": "To complete",
    "status": "Status",
    "paid": "Paid / reimbursed",
    "outstanding": "Balance",
    "payment": "Record payment",
    "paymentHelp": "Amount actually received, paid or reimbursed. No banking operation.",
    "print": "Print / save PDF",
    "cancel": "Cancel this record",
    "reason": "Cancellation reason",
    "source": "Original document",
    "raw": "Recognized text — review required",
    "summaryHelp": "Planned bookings, issued invoices and payments are separate. Drafts are excluded from totals.",
    "income": "Invoiced",
    "costs": "Reviewed purchases & expenses",
    "received": "Recorded receipts",
    "spent": "Recorded outgoing payments",
    "search": "Search records",
    "month": "Month (optional)",
    "local": "Data in this browser. Export to keep a copy.",
    "account": "Private account records.",
    "importHelp": "Photos or PDFs: 5 MB each, 10 files and 20 MB per batch. Read on this device, without an external service. Each selected area creates a draft to review.",
    "files": "Choose photos or PDFs",
    "camera": "Take a photo",
    "prepare": "Prepare documents",
    "reading": "Reading…",
    "recognize": "Read and create drafts",
    "cropHelp": "Several bills in the photo? Draw an area around each, or adjust its coordinates in %. Remove unwanted areas. The original stays intact.",
    "area": "Area",
    "addArea": "Add area",
    "page": "Page",
    "x": "Left (%)",
    "y": "Top (%)",
    "width": "Width (%)",
    "height": "Height (%)",
    "ocrHelp": "Suggestions may be wrong. Check each original before confirming. Uncertain fields remain incomplete.",
    "fileError": "Unreadable file, unsupported format or limit exceeded. Nothing was saved.",
    "duplicate": "This document is already saved. Open its records in the ledger.",
    "ocrFailed": "Automatic reading unavailable. Keep originals and complete drafts manually.",
    "manualImport": "Keep without recognition",
    "noBookings": "No saved booking to add.",
    "exportError": "Export incomplete: an original or workbook could not be read. No partial file downloaded.",
    "allExport": "Export includes all records, including drafts and cancellations, and every original.",
    "sourceFile": "Source file",
    "payments": "Payments",
    "lines": "Lines",
    "readme": "Read me",
    "savePayment": "Save payment",
    "profile": "Billing details",
    "keepProfile": "Reuse these details for future invoices",
    "adjustAreas": "Adjust areas",
    "previewFailed": "PDF preview unavailable. Keep the original with a manual draft, without assuming a page or area.",
    "pendingDraft": "Your edits remain here while this page stays open. Resume or discard them before opening another record.",
    "resumeHelp": "Return to the open record.",
    "resume": "Resume record",
    "discard": "Discard edits",
    "resumeImport": "Resume documents",
    "discardImport": "Discard selected documents",
    "pendingImport": "Documents are already waiting. Keep or discard them before selecting others.",
    "unavailable": "Accounting unavailable. Records could not be loaded. Saving and export are disabled. Retry; if necessary, reload the page.",
    "retry": "Retry",
    "saveEditsFirst": "Save or discard the record edits before adding a payment."
  },
  "it": {
    "title": "Contabilità",
    "journal": "Registro",
    "invoices": "Fatture clienti",
    "expenses": "Acquisti e spese",
    "review": "Da verificare",
    "rates": "Prenotazioni e tariffe",
    "sale": "Fattura cliente",
    "purchase": "Fattura fornitore",
    "expense": "Nota spese",
    "extra": "Extra fatturato",
    "newInvoice": "Nuova fattura",
    "newExpense": "Aggiungi spesa",
    "import": "Aggiungi giustificativi",
    "export": "Esporta per il contabile",
    "exportHelp": "Excel e originali in un file ZIP. Nulla viene inviato.",
    "empty": "Nessuna registrazione. Aggiungi fattura o documento.",
    "draft": "Bozza",
    "confirmed": "Verificato",
    "issued": "Emessa",
    "cancelled": "Annullato",
    "kind": "Tipo",
    "number": "Numero / riferimento",
    "date": "Data",
    "due": "Scadenza",
    "party": "Cliente / fornitore / beneficiario",
    "address": "Indirizzo cliente",
    "issuer": "La tua attività",
    "issuerAddress": "Indirizzo attività",
    "taxId": "Codice fiscale (facoltativo)",
    "currency": "Valuta",
    "category": "Categoria",
    "service": "Prestazione",
    "supplies": "Forniture",
    "food": "Alimentazione",
    "transport": "Trasporto",
    "health": "Veterinario",
    "equipment": "Attrezzatura",
    "insurance": "Assicurazione",
    "other": "Da classificare / altro",
    "description": "Descrizione",
    "quantity": "Quantità",
    "unit": "Prezzo unitario, IVA inclusa",
    "amount": "Importo, IVA inclusa",
    "vat": "Di cui IVA (facoltativa)",
    "note": "Nota",
    "addLine": "Aggiungi riga / extra",
    "remove": "Rimuovi",
    "booking": "Aggiungi prenotazione salvata",
    "choose": "Scegli",
    "save": "Salva bozza",
    "confirm": "Verifica e salva",
    "issue": "Emetti fattura",
    "issueHelp": "Verifica numero, dati e importi. Dopo l’emissione restano fissi. Nessun invio automatico.",
    "unsaved": "Salva prima di chiudere o ricaricare: le modifiche non salvate andranno perse.",
    "back": "Torna al registro",
    "edit": "Apri / modifica",
    "saved": "Salvato",
    "error": "Non salvato. Verifica campi, connessione e spazio. Se i dati sono cambiati altrove, copia la bozza e ricarica.",
    "unknown": "Da completare",
    "status": "Stato",
    "paid": "Pagato / rimborsato",
    "outstanding": "Saldo",
    "payment": "Registra pagamento",
    "paymentHelp": "Importo realmente ricevuto, pagato o rimborsato. Nessuna operazione bancaria.",
    "print": "Stampa / salva PDF",
    "cancel": "Annulla registrazione",
    "reason": "Motivo annullamento",
    "source": "Documento originale",
    "raw": "Testo riconosciuto — da verificare",
    "summaryHelp": "Prenotazioni previste, fatture emesse e pagamenti sono distinti. Bozze escluse dai totali.",
    "income": "Fatturato",
    "costs": "Acquisti e spese verificati",
    "received": "Incassi registrati",
    "spent": "Uscite registrate",
    "search": "Cerca registrazioni",
    "month": "Mese (facoltativo)",
    "local": "Dati in questo browser. Esporta per conservarne una copia.",
    "account": "Dati privati del tuo account.",
    "importHelp": "Foto o PDF: 5 MB ciascuno, 10 file e 20 MB per gruppo. Lettura sul dispositivo, senza servizi esterni. Ogni area crea una bozza da verificare.",
    "files": "Scegli foto o PDF",
    "camera": "Scatta foto",
    "prepare": "Prepara documenti",
    "reading": "Lettura…",
    "recognize": "Leggi e crea bozze",
    "cropHelp": "Più fatture nella foto? Disegna un’area per ciascuna o regola le coordinate in %. Rimuovi aree inutili. Originale intatto.",
    "area": "Area",
    "addArea": "Aggiungi area",
    "page": "Pagina",
    "x": "Sinistra (%)",
    "y": "Alto (%)",
    "width": "Larghezza (%)",
    "height": "Altezza (%)",
    "ocrHelp": "I suggerimenti possono essere errati. Controlla gli originali prima di confermare. Campi incerti da completare.",
    "fileError": "File illeggibile, formato non supportato o limite superato. Nulla salvato.",
    "duplicate": "Documento già salvato. Apri le registrazioni nel registro.",
    "ocrFailed": "Lettura automatica non disponibile. Conserva originali e completa bozze a mano.",
    "manualImport": "Conserva senza riconoscimento",
    "noBookings": "Nessuna prenotazione salvata.",
    "exportError": "Esportazione incompleta: originale o cartella non leggibile. Nessun file parziale scaricato.",
    "allExport": "Export include tutte le registrazioni, bozze, annullamenti e originali.",
    "sourceFile": "File origine",
    "payments": "Pagamenti",
    "lines": "Righe",
    "readme": "Leggimi",
    "savePayment": "Salva pagamento",
    "profile": "Dati fatturazione",
    "keepProfile": "Riutilizza dati per prossime fatture",
    "adjustAreas": "Regola le aree",
    "previewFailed": "Anteprima PDF non disponibile. Conserva l’originale con una bozza manuale, senza presumere pagina o area.",
    "pendingDraft": "Le modifiche restano qui finché la pagina è aperta. Riprendile o scartale prima di aprire un’altra registrazione.",
    "resumeHelp": "Torna alla registrazione aperta.",
    "resume": "Riprendi registrazione",
    "discard": "Scarta modifiche",
    "resumeImport": "Riprendi documenti",
    "discardImport": "Scarta documenti selezionati",
    "pendingImport": "Ci sono già documenti in attesa. Conservali o scartali prima di selezionarne altri.",
    "unavailable": "Contabilità non disponibile. Impossibile caricare le registrazioni. Salvataggio ed esportazione disattivati. Riprova; se necessario, ricarica la pagina.",
    "retry": "Riprova",
    "saveEditsFirst": "Salva o scarta le modifiche alla registrazione prima di aggiungere un pagamento."
  },
  "de": {
    "title": "Buchhaltung",
    "journal": "Journal",
    "invoices": "Kundenrechnungen",
    "expenses": "Einkäufe & Ausgaben",
    "review": "Prüfen",
    "rates": "Buchungen & Tarife",
    "sale": "Kundenrechnung",
    "purchase": "Lieferantenrechnung",
    "expense": "Spesenabrechnung",
    "extra": "Berechnetes Extra",
    "newInvoice": "Neue Rechnung",
    "newExpense": "Ausgabe hinzufügen",
    "import": "Belege hinzufügen",
    "export": "Für Buchhaltung exportieren",
    "exportHelp": "Excel-Datei und Originale als ZIP. Es wird nichts versendet.",
    "empty": "Noch keine Einträge. Rechnung oder Beleg hinzufügen.",
    "draft": "Entwurf",
    "confirmed": "Geprüft",
    "issued": "Ausgestellt",
    "cancelled": "Storniert",
    "kind": "Art",
    "number": "Nummer / Referenz",
    "date": "Datum",
    "due": "Fällig am",
    "party": "Kunde / Lieferant / Empfänger",
    "address": "Kundenadresse",
    "issuer": "Ihr Unternehmen",
    "issuerAddress": "Geschäftsadresse",
    "taxId": "Steuernummer (optional)",
    "currency": "Währung",
    "category": "Kategorie",
    "service": "Dienstleistung",
    "supplies": "Verbrauchsmaterial",
    "food": "Futter",
    "transport": "Transport",
    "health": "Tierarzt",
    "equipment": "Ausrüstung",
    "insurance": "Versicherung",
    "other": "Unzugeordnet / sonstiges",
    "description": "Beschreibung",
    "quantity": "Menge",
    "unit": "Einzelpreis inkl. Steuer",
    "amount": "Betrag inkl. Steuer",
    "vat": "Enthaltene Steuer (optional)",
    "note": "Notiz",
    "addLine": "Zeile / Extra hinzufügen",
    "remove": "Entfernen",
    "booking": "Gespeicherte Buchung hinzufügen",
    "choose": "Auswählen",
    "save": "Entwurf speichern",
    "confirm": "Prüfen und speichern",
    "issue": "Rechnung ausstellen",
    "issueHelp": "Nummer, Angaben und Beträge prüfen. Nach Ausstellung unveränderlich. Kein automatischer Versand.",
    "unsaved": "Vor dem Schließen oder Neuladen speichern: Ungespeicherte Änderungen gehen verloren.",
    "back": "Zurück zum Journal",
    "edit": "Öffnen / bearbeiten",
    "saved": "Gespeichert",
    "error": "Nicht gespeichert. Felder, Verbindung und Speicher prüfen. Bei Änderungen in anderem Fenster Entwurf kopieren und neu laden.",
    "unknown": "Ergänzen",
    "status": "Status",
    "paid": "Bezahlt / erstattet",
    "outstanding": "Restbetrag",
    "payment": "Zahlung erfassen",
    "paymentHelp": "Tatsächlich erhaltener, bezahlter oder erstatteter Betrag. Keine Banktransaktion.",
    "print": "Drucken / als PDF speichern",
    "cancel": "Eintrag stornieren",
    "reason": "Stornogrund",
    "source": "Originalbeleg",
    "raw": "Erkannter Text — bitte prüfen",
    "summaryHelp": "Geplante Buchungen, Rechnungen und Zahlungen sind getrennt. Entwürfe zählen nicht mit.",
    "income": "In Rechnung gestellt",
    "costs": "Geprüfte Einkäufe & Ausgaben",
    "received": "Erfasste Einnahmen",
    "spent": "Erfasste Auszahlungen",
    "search": "Einträge suchen",
    "month": "Monat (optional)",
    "local": "Daten in diesem Browser. Für eine Kopie exportieren.",
    "account": "Private Kontodaten.",
    "importHelp": "Fotos oder PDF: je 5 MB, 10 Dateien und 20 MB je Stapel. Verarbeitung auf diesem Gerät, ohne externen Dienst. Jeder Bereich wird ein Prüfentwurf.",
    "files": "Fotos oder PDFs auswählen",
    "camera": "Foto aufnehmen",
    "prepare": "Dokumente vorbereiten",
    "reading": "Wird gelesen…",
    "recognize": "Lesen und Entwürfe erstellen",
    "cropHelp": "Mehrere Belege im Foto? Jeden Bereich markieren oder Koordinaten in % anpassen. Unnötige Bereiche entfernen. Original bleibt erhalten.",
    "area": "Bereich",
    "addArea": "Bereich hinzufügen",
    "page": "Seite",
    "x": "Links (%)",
    "y": "Oben (%)",
    "width": "Breite (%)",
    "height": "Höhe (%)",
    "ocrHelp": "Vorschläge können falsch sein. Originale vor Bestätigung prüfen. Unsichere Felder bleiben offen.",
    "fileError": "Datei unlesbar, Format nicht unterstützt oder Grenze überschritten. Nichts gespeichert.",
    "duplicate": "Beleg bereits gespeichert. Einträge im Journal öffnen.",
    "ocrFailed": "Automatisches Lesen nicht verfügbar. Originale behalten und Entwürfe manuell ergänzen.",
    "manualImport": "Ohne Erkennung speichern",
    "noBookings": "Keine gespeicherte Buchung vorhanden.",
    "exportError": "Export unvollständig: Original oder Arbeitsmappe nicht lesbar. Keine Teildatei heruntergeladen.",
    "allExport": "Export enthält alle Einträge, Entwürfe, Stornos und Originale.",
    "sourceFile": "Quelldatei",
    "payments": "Zahlungen",
    "lines": "Zeilen",
    "readme": "Hinweise",
    "savePayment": "Zahlung speichern",
    "profile": "Rechnungsangaben",
    "keepProfile": "Angaben für künftige Rechnungen verwenden",
    "adjustAreas": "Bereiche anpassen",
    "previewFailed": "PDF-Vorschau nicht verfügbar. Original mit manuellem Entwurf behalten, ohne Seite oder Bereich anzunehmen.",
    "pendingDraft": "Änderungen bleiben erhalten, solange diese Seite geöffnet ist. Vor einem anderen Eintrag fortsetzen oder verwerfen.",
    "resumeHelp": "Zum geöffneten Eintrag zurückkehren.",
    "resume": "Eintrag fortsetzen",
    "discard": "Änderungen verwerfen",
    "resumeImport": "Belege fortsetzen",
    "discardImport": "Ausgewählte Belege verwerfen",
    "pendingImport": "Belege warten bereits. Vor der nächsten Auswahl behalten oder verwerfen.",
    "unavailable": "Buchhaltung nicht verfügbar. Einträge konnten nicht geladen werden. Speichern und Export sind deaktiviert. Erneut versuchen; bei Bedarf Seite neu laden.",
    "retry": "Erneut versuchen",
    "saveEditsFirst": "Änderungen am Eintrag speichern oder verwerfen, bevor eine Zahlung hinzugefügt wird."
  },
  "es": {
    "title": "Contabilidad",
    "journal": "Registro",
    "invoices": "Facturas de clientes",
    "expenses": "Compras y gastos",
    "review": "Por revisar",
    "rates": "Reservas y tarifas",
    "sale": "Factura de cliente",
    "purchase": "Factura de proveedor",
    "expense": "Nota de gastos",
    "extra": "Extra facturado",
    "newInvoice": "Nueva factura",
    "newExpense": "Añadir gasto",
    "import": "Añadir justificantes",
    "export": "Exportar para contable",
    "exportHelp": "Excel y originales en ZIP. No se envía nada.",
    "empty": "Sin registros. Añade una factura o justificante.",
    "draft": "Borrador",
    "confirmed": "Revisado",
    "issued": "Emitida",
    "cancelled": "Anulado",
    "kind": "Tipo",
    "number": "Número / referencia",
    "date": "Fecha",
    "due": "Vencimiento",
    "party": "Cliente / proveedor / beneficiario",
    "address": "Dirección del cliente",
    "issuer": "Tu empresa",
    "issuerAddress": "Dirección de la empresa",
    "taxId": "Identificación fiscal (opcional)",
    "currency": "Moneda",
    "category": "Categoría",
    "service": "Servicio",
    "supplies": "Suministros",
    "food": "Alimentación",
    "transport": "Transporte",
    "health": "Veterinario",
    "equipment": "Equipo",
    "insurance": "Seguro",
    "other": "Sin clasificar / otro",
    "description": "Concepto",
    "quantity": "Cantidad",
    "unit": "Precio unitario, impuestos incluidos",
    "amount": "Importe, impuestos incluidos",
    "vat": "Impuestos incluidos (opcional)",
    "note": "Nota",
    "addLine": "Añadir línea / extra",
    "remove": "Quitar",
    "booking": "Añadir reserva guardada",
    "choose": "Elegir",
    "save": "Guardar borrador",
    "confirm": "Revisar y guardar",
    "issue": "Emitir factura",
    "issueHelp": "Revisa número, datos e importes. Una vez emitida, quedan fijados. Sin envío automático.",
    "unsaved": "Guarda antes de cerrar o recargar: se perderán los cambios sin guardar.",
    "back": "Volver al registro",
    "edit": "Abrir / editar",
    "saved": "Guardado",
    "error": "No guardado. Revisa campos, conexión y espacio. Si los datos cambiaron en otra ventana, copia el borrador y recarga.",
    "unknown": "Por completar",
    "status": "Estado",
    "paid": "Pagado / reembolsado",
    "outstanding": "Saldo",
    "payment": "Registrar pago",
    "paymentHelp": "Importe recibido, pagado o reembolsado realmente. Sin operación bancaria.",
    "print": "Imprimir / guardar PDF",
    "cancel": "Anular registro",
    "reason": "Motivo de anulación",
    "source": "Justificante original",
    "raw": "Texto reconocido — por revisar",
    "summaryHelp": "Reservas previstas, facturas emitidas y pagos son distintos. Borradores excluidos de totales.",
    "income": "Facturado",
    "costs": "Compras y gastos revisados",
    "received": "Cobros registrados",
    "spent": "Pagos registrados",
    "search": "Buscar registros",
    "month": "Mes (opcional)",
    "local": "Datos en este navegador. Exporta para conservar copia.",
    "account": "Datos privados de tu cuenta.",
    "importHelp": "Fotos o PDF: 5 MB cada uno, 10 archivos y 20 MB por lote. Lectura en este dispositivo, sin servicio externo. Cada zona crea un borrador para revisar.",
    "files": "Elegir fotos o PDF",
    "camera": "Tomar foto",
    "prepare": "Preparar documentos",
    "reading": "Leyendo…",
    "recognize": "Leer y crear borradores",
    "cropHelp": "¿Varias facturas en la foto? Dibuja una zona por cada una o ajusta coordenadas en %. Quita zonas sobrantes. Original intacto.",
    "area": "Zona",
    "addArea": "Añadir zona",
    "page": "Página",
    "x": "Izquierda (%)",
    "y": "Arriba (%)",
    "width": "Ancho (%)",
    "height": "Alto (%)",
    "ocrHelp": "Las sugerencias pueden ser erróneas. Revisa originales antes de confirmar. Campos inciertos quedan incompletos.",
    "fileError": "Archivo ilegible, formato no compatible o límite superado. Nada guardado.",
    "duplicate": "Justificante ya guardado. Abre sus registros.",
    "ocrFailed": "Lectura automática no disponible. Conserva originales y completa borradores a mano.",
    "manualImport": "Conservar sin reconocimiento",
    "noBookings": "No hay reservas guardadas.",
    "exportError": "Exportación incompleta: original o libro ilegible. Ningún archivo parcial descargado.",
    "allExport": "Exportación incluye todos los registros, borradores, anulaciones y originales.",
    "sourceFile": "Archivo origen",
    "payments": "Pagos",
    "lines": "Líneas",
    "readme": "Léeme",
    "savePayment": "Guardar pago",
    "profile": "Datos de facturación",
    "keepProfile": "Reutilizar datos en próximas facturas",
    "adjustAreas": "Ajustar zonas",
    "previewFailed": "Vista previa del PDF no disponible. Conserva el original con un borrador manual, sin suponer página ni zona.",
    "pendingDraft": "Los cambios se conservan mientras la página siga abierta. Retómalos o descártalos antes de abrir otro registro.",
    "resumeHelp": "Volver al registro abierto.",
    "resume": "Retomar registro",
    "discard": "Descartar cambios",
    "resumeImport": "Retomar justificantes",
    "discardImport": "Descartar justificantes seleccionados",
    "pendingImport": "Ya hay justificantes pendientes. Consérvalos o descártalos antes de seleccionar otros.",
    "unavailable": "Contabilidad no disponible. No se pudieron cargar los registros. Guardado y exportación desactivados. Reintenta; si hace falta, recarga la página.",
    "retry": "Reintentar",
    "saveEditsFirst": "Guarda o descarta los cambios del registro antes de añadir un pago."
  }
};
