/* Labels for educational browsing and explicitly private, unreviewed experience. */
window.KnowledgeCopy = {
  fr: {
    title:'Maison de la Santé', intro:'Des gestes du quotidien, des repères fiables et vos savoirs d’expérience.',
    all:'Tout voir', practices:'Bonnes pratiques', traditional:'Conseils de grand-mère', colleague:'Expériences de collègues', videos:'Vidéos et tutos',
    search:'Rechercher un sujet ou une expérience', guided:'Par où commencer ?', observe:'Mieux observer', gesture:'Apprendre un geste', visit:'Préparer une visite',
    guide:'Guide sourcé', draft:'Brouillon privé · expérience non relue', draftHelp:'Un vécu à garder en contexte, pas une recommandation de soin validée. Rien n’est publié ni envoyé.',
    read:'Ouvrir le guide', back:'Retour aux ressources', sources:'Sources', checked:'Sources consultées le', sourceLanguage:'Langue de la source',
    add:'Ajouter une expérience', edit:'Modifier', save:'Enregistrer le brouillon', cancel:'Annuler', experienceTitle:'Titre', body:'Ce qui a été observé, dans quel contexte',
    author:'Attribution (facultative)', link:'Lien source ou vidéo (facultatif)', category:'Rubrique', noResults:'Aucun résultat pour ce choix.',
    empty:'Votre expérience a sa place ici. Ajoutez un premier récit privé avec son contexte et, si vous en avez un, son lien source.',
    saved:'Brouillon privé enregistré', sourceProvided:'Lien fourni avec cette expérience', steps:'En pratique', watch:'Voir chez le fournisseur',
    invalid:'Vérifiez le titre, le texte et le lien (http ou https, sans identifiants). Rien n’a été enregistré.',
    accountStorage:'Vos expériences : privées dans le compte de votre activité.', browserStorage:'Vos expériences : privées dans ce navigateur uniquement.',
    loadError:'Ces expériences n’ont pas pu être chargées. Rechargez avant de modifier les données.',
    saveError:'Non enregistré. Votre saisie est conservée ici. Copiez-la avant de recharger si les données ou le compte ont changé.',
    stale:'Non enregistré : les expériences ont changé dans un autre onglet. Copiez votre saisie, puis rechargez pour retrouver les dernières données.',
    locking:'Ce navigateur ne permet pas un enregistrement sûr entre onglets. Votre saisie reste ici ; utilisez un navigateur récent.',
    learning:'Choisissez un sujet à explorer. Ces choix ouvrent des ressources, sans établir de diagnostic.', count:'ressources',
  },
  en: {
    title:'Care & wellbeing', intro:'Everyday care, sourced guidance and your practical experience.',
    all:'Show all', practices:'Good practices', traditional:'Traditional tips', colleague:'Carers’ experiences', videos:'Videos and tutorials',
    search:'Search a topic or experience', guided:'Where to start?', observe:'Observe more closely', gesture:'Learn a care routine', visit:'Prepare a vet visit',
    guide:'Sourced guide', draft:'Private draft · unreviewed experience', draftHelp:'Keep this experience in context; it is not validated care advice. Nothing is published or sent.',
    read:'Open guide', back:'Back to resources', sources:'Sources', checked:'Sources checked on', sourceLanguage:'Source language',
    add:'Add an experience', edit:'Edit', save:'Save private draft', cancel:'Cancel', experienceTitle:'Title', body:'What was observed, and in what context',
    author:'Attribution (optional)', link:'Source or video link (optional)', category:'Category', noResults:'No results for this choice.',
    empty:'Your experience belongs here. Add a first private account with its context and a source link if you have one.',
    saved:'Private draft saved', sourceProvided:'Link supplied with this experience', steps:'In practice', watch:'Watch on provider site',
    invalid:'Check the title, text and link (http or https, without credentials). Nothing was saved.',
    accountStorage:'Your experiences: private within your business account.', browserStorage:'Your experiences: private in this browser only.',
    loadError:'These experiences could not be loaded. Reload before changing records.',
    saveError:'Not saved. Your entries remain here. Copy them before reloading if the records or account changed.',
    stale:'Not saved: experiences changed in another tab. Copy your entries, then reload to get the latest records.',
    locking:'This browser cannot safely coordinate saves across tabs. Your entries remain here; use a current browser.',
    learning:'Choose a topic to explore. These choices open resources, without making a diagnosis.', count:'resources',
  },
  it: {
    title:'Casa della salute', intro:'Gesti quotidiani, indicazioni documentate e la vostra esperienza.',
    all:'Mostra tutto', practices:'Buone pratiche', traditional:'Consigli della nonna', colleague:'Esperienze dei colleghi', videos:'Video e tutorial',
    search:'Cerca un argomento o un’esperienza', guided:'Da dove iniziare?', observe:'Osservare meglio', gesture:'Imparare un gesto', visit:'Preparare una visita',
    guide:'Guida con fonti', draft:'Bozza privata · esperienza non revisionata', draftHelp:'Un’esperienza da tenere nel suo contesto, non un consiglio di cura validato. Nulla viene pubblicato o inviato.',
    read:'Apri la guida', back:'Torna alle risorse', sources:'Fonti', checked:'Fonti consultate il', sourceLanguage:'Lingua della fonte',
    add:'Aggiungi un’esperienza', edit:'Modifica', save:'Salva la bozza privata', cancel:'Annulla', experienceTitle:'Titolo', body:'Cosa è stato osservato e in quale contesto',
    author:'Attribuzione (facoltativa)', link:'Link alla fonte o al video (facoltativo)', category:'Categoria', noResults:'Nessun risultato per questa scelta.',
    empty:'La vostra esperienza trova spazio qui. Aggiungete un primo racconto privato con il contesto e, se disponibile, un link alla fonte.',
    saved:'Bozza privata salvata', sourceProvided:'Link fornito con questa esperienza', steps:'In pratica', watch:'Guarda sul sito del fornitore',
    invalid:'Controllate titolo, testo e link (http o https, senza credenziali). Nulla è stato salvato.',
    accountStorage:'Le vostre esperienze: private nell’account della vostra attività.', browserStorage:'Le vostre esperienze: private solo in questo browser.',
    loadError:'Non è stato possibile caricare le esperienze. Ricaricate prima di modificare i dati.',
    saveError:'Non salvato. I dati inseriti restano qui. Copiateli prima di ricaricare se i dati o l’account sono cambiati.',
    stale:'Non salvato: le esperienze sono cambiate in un’altra scheda. Copiate il testo, poi ricaricate i dati aggiornati.',
    locking:'Questo browser non può coordinare i salvataggi tra schede. Il testo resta qui; usate un browser aggiornato.',
    learning:'Scegliete un argomento da esplorare. Queste scelte aprono risorse, senza formulare diagnosi.', count:'risorse',
  },
  de: {
    title:'Haus der Gesundheit', intro:'Alltagspflege, belegte Hinweise und eure Erfahrungen.',
    all:'Alle anzeigen', practices:'Gute Praxis', traditional:'Überlieferte Tipps', colleague:'Erfahrungen von Kollegen', videos:'Videos und Anleitungen',
    search:'Thema oder Erfahrung suchen', guided:'Wo anfangen?', observe:'Genauer beobachten', gesture:'Einen Handgriff lernen', visit:'Tierarztbesuch vorbereiten',
    guide:'Ratgeber mit Quellen', draft:'Privater Entwurf · ungeprüfte Erfahrung', draftHelp:'Eine Erfahrung mit ihrem Kontext, keine bestätigte Pflegeempfehlung. Nichts wird veröffentlicht oder versendet.',
    read:'Ratgeber öffnen', back:'Zurück zu den Ressourcen', sources:'Quellen', checked:'Quellen geprüft am', sourceLanguage:'Sprache der Quelle',
    add:'Erfahrung hinzufügen', edit:'Bearbeiten', save:'Privaten Entwurf speichern', cancel:'Abbrechen', experienceTitle:'Titel', body:'Was wurde in welchem Zusammenhang beobachtet?',
    author:'Urheberangabe (optional)', link:'Quellen- oder Videolink (optional)', category:'Kategorie', noResults:'Keine Ergebnisse für diese Auswahl.',
    empty:'Hier ist Platz für eure Erfahrung. Fügt einen ersten privaten Bericht mit Kontext und gegebenenfalls einem Quellenlink hinzu.',
    saved:'Privater Entwurf gespeichert', sourceProvided:'Zu dieser Erfahrung angegebener Link', steps:'In der Praxis', watch:'Beim Anbieter ansehen',
    invalid:'Prüft Titel, Text und Link (http oder https, ohne Zugangsdaten). Nichts wurde gespeichert.',
    accountStorage:'Eure Erfahrungen: privat im Konto eures Betriebs.', browserStorage:'Eure Erfahrungen: nur in diesem Browser privat gespeichert.',
    loadError:'Die Erfahrungen konnten nicht geladen werden. Vor Änderungen bitte neu laden.',
    saveError:'Nicht gespeichert. Eure Eingaben bleiben hier. Kopiert sie vor dem Neuladen, falls Daten oder Konto geändert wurden.',
    stale:'Nicht gespeichert: Erfahrungen wurden in einem anderen Tab geändert. Kopiert eure Eingaben und ladet die aktuellen Daten neu.',
    locking:'Dieser Browser kann Speichern zwischen Tabs nicht sicher koordinieren. Eingaben bleiben hier; verwendet einen aktuellen Browser.',
    learning:'Wählt ein Thema. Die Auswahl öffnet Lernmaterial und stellt keine Diagnose.', count:'Ressourcen',
  },
  es: {
    title:'Casa de la salud', intro:'Cuidados cotidianos, orientación con fuentes y vuestra experiencia.',
    all:'Ver todo', practices:'Buenas prácticas', traditional:'Consejos de la abuela', colleague:'Experiencias de compañeros', videos:'Vídeos y tutoriales',
    search:'Buscar un tema o una experiencia', guided:'¿Por dónde empezar?', observe:'Observar mejor', gesture:'Aprender un gesto', visit:'Preparar una visita',
    guide:'Guía con fuentes', draft:'Borrador privado · experiencia sin revisar', draftHelp:'Una experiencia con su contexto, no un consejo de cuidado validado. No se publica ni se envía nada.',
    read:'Abrir la guía', back:'Volver a los recursos', sources:'Fuentes', checked:'Fuentes consultadas el', sourceLanguage:'Idioma de la fuente',
    add:'Añadir una experiencia', edit:'Editar', save:'Guardar el borrador privado', cancel:'Cancelar', experienceTitle:'Título', body:'Qué se observó y en qué contexto',
    author:'Atribución (opcional)', link:'Enlace a fuente o vídeo (opcional)', category:'Categoría', noResults:'No hay resultados para esta selección.',
    empty:'Vuestra experiencia tiene su lugar aquí. Añadid un primer relato privado con su contexto y un enlace a la fuente si lo tenéis.',
    saved:'Borrador privado guardado', sourceProvided:'Enlace aportado con esta experiencia', steps:'En la práctica', watch:'Ver en la web del proveedor',
    invalid:'Revisad el título, el texto y el enlace (http o https, sin credenciales). No se ha guardado nada.',
    accountStorage:'Vuestras experiencias: privadas en la cuenta de vuestra actividad.', browserStorage:'Vuestras experiencias: privadas solo en este navegador.',
    loadError:'No se han podido cargar las experiencias. Recargad antes de modificar los datos.',
    saveError:'No guardado. Los datos introducidos siguen aquí. Copiadlos antes de recargar si los datos o la cuenta han cambiado.',
    stale:'No guardado: las experiencias han cambiado en otra pestaña. Copiad el texto y recargad los datos actualizados.',
    locking:'Este navegador no puede coordinar guardados entre pestañas de forma segura. El texto sigue aquí; usad un navegador actualizado.',
    learning:'Elegid un tema para explorar. Las opciones abren recursos, sin establecer un diagnóstico.', count:'recursos',
  }
};
