(function (w) {
  const languages=['en','fr','it','de','es'];
  const rows={
    videoSizeError:['The video is empty or larger than 80 MiB.','Vidéo vide ou supérieure à 80 Mio.','Video vuoto o superiore a 80 MiB.','Das Video ist leer oder größer als 80 MiB.','Vídeo vacío o de más de 80 MiB.'],
    photoSizeError:['The photo is empty or larger than 12 MiB.','Photo vide ou supérieure à 12 Mio.','Foto vuota o superiore a 12 MiB.','Das Foto ist leer oder größer als 12 MiB.','Foto vacía o de más de 12 MiB.'],
    formatError:['Choose a JPEG, PNG, WebP, HEIC photo or MP4, MOV, WebM video.','Choisissez une photo JPEG, PNG, WebP, HEIC ou une vidéo MP4, MOV, WebM.','Scegli una foto JPEG, PNG, WebP, HEIC o un video MP4, MOV, WebM.','Wähle ein JPEG-, PNG-, WebP-, HEIC-Foto oder MP4-, MOV-, WebM-Video.','Elige una foto JPEG, PNG, WebP, HEIC o un vídeo MP4, MOV, WebM.'],
    photoFormatError:['Choose a JPEG, PNG, WebP or HEIC photo.','Choisissez une photo JPEG, PNG, WebP ou HEIC.','Scegli una foto JPEG, PNG, WebP o HEIC.','Wähle ein Foto in JPEG, PNG, WebP oder HEIC.','Elige una foto JPEG, PNG, WebP o HEIC.'],
    photoLimits:['Photos up to 12 MiB.','Photos jusqu’à 12 Mio.','Foto fino a 12 MiB.','Fotos bis 12 MiB.','Fotos de hasta 12 MiB.'],
    album:['Private album','Album privé','Album privato','Privates Album','Álbum privado'],
    add:['Add photos or videos','Ajouter des photos ou vidéos','Aggiungi foto o video','Fotos oder Videos hinzufügen','Añadir fotos o vídeos'],
    camera:['Take a photo','Prendre une photo','Scatta una foto','Foto aufnehmen','Hacer una foto'],
    empty:['No photos or videos yet.','Pas encore de photo ou vidéo.','Ancora nessuna foto o video.','Noch keine Fotos oder Videos.','Todavía no hay fotos ni vídeos.'],
    privacy:['Visible only to your family and your dog-sitter.','Visible uniquement par votre famille et votre dog-sitter.','Visibile solo alla tua famiglia e alla tua dog-sitter.','Nur für deine Familie und deine Dog-Sitterin sichtbar.','Visible solo para tu familia y tu dog-sitter.'],
    limits:['12 MiB per photo · 80 MiB per video.','12 Mio par photo · 80 Mio par vidéo.','12 MiB per foto · 80 MiB per video.','12 MiB pro Foto · 80 MiB pro Video.','12 MiB por foto · 80 MiB por vídeo.'],
    cover:['Use as profile photo','Choisir comme photo de profil','Usa come foto profilo','Als Profilfoto wählen','Elegir como foto de perfil'],
    selected:['Profile photo','Photo de profil','Foto profilo','Profilfoto','Foto de perfil'],
    remove:['Remove','Supprimer','Elimina','Löschen','Eliminar'],
    confirm:['Remove this media?','Supprimer ce média ?','Eliminare questo contenuto?','Dieses Medium löschen?','¿Eliminar este archivo?'],
    open:['Open','Ouvrir','Apri','Öffnen','Abrir'],
    close:['Close','Fermer','Chiudi','Schließen','Cerrar'],
    download:['Download file','Télécharger le fichier','Scarica il file','Datei herunterladen','Descargar archivo'],
    uploading:['Uploading','Transfert','Caricamento','Übertragung','Subiendo'],
    checking:['Preparing the file…','Préparation du fichier…','Preparazione del file…','Datei wird vorbereitet…','Preparando el archivo…'],
    draftSaved:['Photo saved privately · save appearance to publish','Photo ajoutée en privé · enregistrez l’apparence pour la publier','Foto salvata in privato · salva l’aspetto per pubblicarla','Foto privat gespeichert · zum Veröffentlichen Aussehen speichern','Foto guardada en privado · guarda la apariencia para publicarla'],
    saved:['Saved','Enregistré','Salvato','Gespeichert','Guardado'],
    homepage:['Homepage photo','Photo de la page d’accueil','Foto della pagina iniziale','Foto der Startseite','Foto de la página de inicio'],
    change:['Change photo','Changer la photo','Cambia foto','Foto ändern','Cambiar foto'],
    publicNotice:['Only saving publishes this selection on the public site. Dog albums remain private.','Seul l’enregistrement publie cette sélection sur le site public. Les albums des chiens restent privés.','Solo il salvataggio pubblica questa selezione sul sito pubblico. Gli album dei cani restano privati.','Erst beim Speichern wird diese Auswahl öffentlich. Hundealben bleiben privat.','Solo guardar publica esta selección en el sitio público. Los álbumes de perros siguen privados.'],
    preview:['Preview','Aperçu','Anteprima','Vorschau','Vista previa'],
    fit:['Framing','Cadrage','Inquadratura','Bildausschnitt','Encuadre'],
    contain:['Whole photo','Photo entière','Foto intera','Ganzes Foto','Foto completa'],
    crop:['Fill the frame','Remplir le cadre','Riempi il riquadro','Rahmen ausfüllen','Llenar el encuadre'],
    position:['Vertical position','Position verticale','Posizione verticale','Vertikale Position','Posición vertical'],
    publish:['Save to website','Enregistrer sur le site','Salva sul sito','Auf Website speichern','Guardar en el sitio'],
    reset:['Reset homepage photo','Rétablir la photo d’origine','Ripristina foto iniziale','Startfoto zurücksetzen','Restablecer foto original'],
    artwork:['Service illustrations','Illustrations des services','Illustrazioni dei servizi','Illustrationen der Angebote','Ilustraciones de servicios'],
    uploadArt:['Add an illustration photo','Ajouter une photo d’illustration','Aggiungi una foto illustrativa','Foto als Illustration hinzufügen','Añadir foto de ilustración'],
    drafts:['My images','Mes images','Le mie immagini','Meine Bilder','Mis imágenes'],
    terrier:['Cheeky terrier','Terrier malicieux','Terrier birichino','Frecher Terrier','Terrier travieso'],
    dalmatian:['Spotted smile','Sourire à pois','Sorriso a pois','Gepunktetes Lächeln','Sonrisa con manchas'],
    pug:['Playful pug','Carlin joueur','Carlino giocherellone','Verspielter Mops','Carlino juguetón'],
    imageError:['This photo cannot be displayed. Choose JPEG, PNG or WebP.','Cette photo ne peut pas être affichée. Choisissez JPEG, PNG ou WebP.','La foto non può essere visualizzata. Scegli JPEG, PNG o WebP.','Dieses Foto kann nicht angezeigt werden. Wähle JPEG, PNG oder WebP.','No se puede mostrar la foto. Elige JPEG, PNG o WebP.'],
    videoError:['This browser cannot play this video. Download it or upload H.264 MP4.','Ce navigateur ne peut pas lire cette vidéo. Téléchargez-la ou ajoutez un MP4 H.264.','Il browser non può riprodurre il video. Scaricalo o carica un MP4 H.264.','Dieser Browser kann das Video nicht abspielen. Lade es herunter oder verwende H.264 MP4.','Este navegador no puede reproducir el vídeo. Descárgalo o sube un MP4 H.264.']
  };
  w.MediaCopy=Object.fromEntries(languages.map((lang,index)=>[lang,Object.fromEntries(Object.entries(rows).map(([key,values])=>[key,values[index]]))]));
})(window);
