(function (w) {
  const languages=['en','fr','it','de','es'];
  const rows={
    album:['Private album','Album privé','Album privato','Privates Album','Álbum privado'],
    add:['Add photos and videos','Ajouter des photos et vidéos','Aggiungi foto e video','Fotos und Videos hinzufügen','Añadir fotos y vídeos'],
    camera:['Take a photo','Prendre une photo','Scatta una foto','Foto aufnehmen','Hacer una foto'],
    empty:['No photos or videos yet.','Pas encore de photo ou vidéo.','Ancora nessuna foto o video.','Noch keine Fotos oder Videos.','Todavía no hay fotos ni vídeos.'],
    privacy:['Visible only to your family and your dog-sitter.','Visible uniquement par votre famille et votre dog-sitter.','Visibile solo alla tua famiglia e alla tua dog-sitter.','Nur für deine Familie und deine Dog-Sitterin sichtbar.','Visible solo para tu familia y tu dog-sitter.'],
    limits:['Photos JPEG, PNG, WebP: 12 MiB. Videos MP4/MOV (H.264) or WebM (VP8/VP9): 80 MiB. HEIC and HEVC are not supported; export JPEG or H.264 from your phone.','Photos JPEG, PNG, WebP : 12 Mio. Vidéos MP4/MOV (H.264) ou WebM (VP8/VP9) : 80 Mio. HEIC et HEVC non pris en charge : exportez en JPEG ou H.264 depuis votre téléphone.','Foto JPEG, PNG, WebP: 12 MiB. Video MP4/MOV (H.264) o WebM (VP8/VP9): 80 MiB. HEIC e HEVC non supportati: esporta in JPEG o H.264 dal telefono.','Fotos JPEG, PNG, WebP: 12 MiB. Videos MP4/MOV (H.264) oder WebM (VP8/VP9): 80 MiB. HEIC und HEVC werden nicht unterstützt; exportiere JPEG oder H.264 vom Handy.','Fotos JPEG, PNG, WebP: 12 MiB. Vídeos MP4/MOV (H.264) o WebM (VP8/VP9): 80 MiB. HEIC y HEVC no compatibles: exporta JPEG o H.264 desde el teléfono.'],
    cover:['Use as profile photo','Choisir comme photo de profil','Usa come foto profilo','Als Profilfoto wählen','Elegir como foto de perfil'],
    selected:['Profile photo','Photo de profil','Foto profilo','Profilfoto','Foto de perfil'],
    remove:['Remove','Supprimer','Elimina','Löschen','Eliminar'],
    confirm:['Remove this media?','Supprimer ce média ?','Eliminare questo contenuto?','Dieses Medium löschen?','¿Eliminar este archivo?'],
    open:['Open','Ouvrir','Apri','Öffnen','Abrir'],
    close:['Close','Fermer','Chiudi','Schließen','Cerrar'],
    download:['Download original','Télécharger l’original','Scarica originale','Original herunterladen','Descargar original'],
    uploading:['Uploading','Transfert','Caricamento','Übertragung','Subiendo'],
    checking:['Checking the file…','Vérification du fichier…','Verifica del file…','Datei wird geprüft…','Comprobando el archivo…'],
    draftSaved:['Photo saved privately · save appearance to publish','Photo ajoutée en privé · enregistrez l’apparence pour la publier','Foto salvata in privato · salva l’aspetto per pubblicarla','Foto privat gespeichert · zum Veröffentlichen Aussehen speichern','Foto guardada en privado · guarda la apariencia para publicarla'],
    saved:['Saved','Enregistré','Salvato','Gespeichert','Guardado'],
    homepage:['Homepage photo','Photo de la page d’accueil','Foto della pagina iniziale','Foto der Startseite','Foto de la página de inicio'],
    change:['Change photo','Changer la photo','Cambia foto','Foto ändern','Cambiar foto'],
    publicNotice:['Only saving publishes this selection on the public site. Dog albums remain private.','Seul l’enregistrement publie cette sélection sur le site public. Les albums des chiens restent privés.','Solo il salvataggio pubblica questa selezione sul sito pubblico. Gli album dei cani restano privati.','Erst beim Speichern wird diese Auswahl öffentlich. Hundealben bleiben privat.','Solo guardar publica esta selección en el sitio público. Los álbumes de perros siguen privados.'],
    preview:['Preview','Aperçu','Anteprima','Vorschau','Vista previa'],
    fit:['Framing','Cadrage','Inquadratura','Bildausschnitt','Encuadre'],
    contain:['Whole photo · keep both dogs visible','Photo entière · garder les deux chiens visibles','Foto intera · entrambi i cani visibili','Ganzes Foto · beide Hunde sichtbar','Foto completa · ambos perros visibles'],
    crop:['Fill the frame','Remplir le cadre','Riempi il riquadro','Rahmen ausfüllen','Llenar el encuadre'],
    position:['Vertical position','Position verticale','Posizione verticale','Vertikale Position','Posición vertical'],
    publish:['Save public appearance','Enregistrer l’apparence publique','Salva aspetto pubblico','Öffentliches Aussehen speichern','Guardar apariencia pública'],
    reset:['Reset homepage photo','Rétablir la photo d’origine','Ripristina foto iniziale','Startfoto zurücksetzen','Restablecer foto original'],
    artwork:['Service illustrations','Illustrations des services','Illustrazioni dei servizi','Illustrationen der Angebote','Ilustraciones de servicios'],
    uploadArt:['Add an illustration photo','Ajouter une photo d’illustration','Aggiungi una foto illustrativa','Foto als Illustration hinzufügen','Añadir foto de ilustración'],
    drafts:['Uploaded appearance photos','Photos d’apparence téléversées','Foto caricate per l’aspetto','Hochgeladene Gestaltungsfotos','Fotos de apariencia subidas'],
    terrier:['Cheeky terrier','Terrier malicieux','Terrier birichino','Frecher Terrier','Terrier travieso'],
    dalmatian:['Spotted smile','Sourire à pois','Sorriso a pois','Gepunktetes Lächeln','Sonrisa con manchas'],
    pug:['Playful pug','Carlin joueur','Carlino giocherellone','Verspielter Mops','Carlino juguetón'],
    imageError:['This photo cannot be displayed. Choose JPEG, PNG or WebP.','Cette photo ne peut pas être affichée. Choisissez JPEG, PNG ou WebP.','La foto non può essere visualizzata. Scegli JPEG, PNG o WebP.','Dieses Foto kann nicht angezeigt werden. Wähle JPEG, PNG oder WebP.','No se puede mostrar la foto. Elige JPEG, PNG o WebP.'],
    videoError:['This browser cannot play this video. Download it or upload H.264 MP4.','Ce navigateur ne peut pas lire cette vidéo. Téléchargez-la ou ajoutez un MP4 H.264.','Il browser non può riprodurre il video. Scaricalo o carica un MP4 H.264.','Dieser Browser kann das Video nicht abspielen. Lade es herunter oder verwende H.264 MP4.','Este navegador no puede reproducir el vídeo. Descárgalo o sube un MP4 H.264.']
  };
  w.MediaCopy=Object.fromEntries(languages.map((lang,index)=>[lang,Object.fromEntries(Object.entries(rows).map(([key,values])=>[key,values[index]]))]));
})(window);
