/* Account navigation and client-facing workflows, in every supported locale. */
(function (w) {
  const locales = ['en','fr','it','de','es'];
  const rows = {
    workspace: ['My space','Mon espace','Il mio spazio','Mein Bereich','Mi espacio'],
    public: ['Public site','Site public','Sito pubblico','Öffentliche Seite','Sitio público'],
    logout: ['Sign out','Se déconnecter','Esci','Abmelden','Cerrar sesión'],
    tools: ['All my tools','Tous mes outils','Tutti i miei strumenti','Alle Werkzeuge','Todas mis herramientas'],
    dogs: ['My dogs','Mes chiens','I miei cani','Meine Hunde','Mis perros'],
    cancelled: ['Cancelled','Annulée','Annullata','Storniert','Cancelada'],
    reservations: ['Reservations','Réservations','Prenotazioni','Reservierungen','Reservas'],
    news: ['Updates','Nouvelles','Novità','Neuigkeiten','Novedades'],
    documents: ['Documents','Documents','Documenti','Dokumente','Documentos'],
    day: ['Day care','Journée de garde','Custodia diurna','Tagesbetreuung','Guardería de día'],
    night: ['Overnight stay','Nuit','Notte','Übernachtung','Noche'],
    walk: ['Walk','Balade','Passeggiata','Spaziergang','Paseo'],
    dayHeading: ['Your day, clearly.','Votre journée, au clair.','La tua giornata, chiara.','Dein Tag im Blick.','Tu día, claro.'],
    noDogs: ['No dog is linked to your access yet. Contact your dog-sitter.','Aucun chien n’est encore lié à votre accès. Contactez votre dog-sitter.','Nessun cane è ancora collegato al tuo accesso. Contatta la tua dog-sitter.','Deinem Zugang ist noch kein Hund zugeordnet. Kontaktiere deine Dog-Sitterin.','Todavía no hay ningún perro vinculado a tu acceso. Contacta con tu dog-sitter.'],
    noBookings: ['No upcoming reservation.','Aucune réservation à venir.','Nessuna prenotazione in programma.','Keine kommende Reservierung.','No hay reservas próximas.'],
    noUpdates: ['No shared updates yet.','Pas encore de nouvelles partagées.','Ancora nessuna novità condivisa.','Noch keine geteilten Neuigkeiten.','Aún no hay novedades compartidas.'],
    noDocuments: ['No documents shared yet.','Aucun document partagé pour le moment.','Ancora nessun documento condiviso.','Noch keine geteilten Dokumente.','Todavía no hay documentos compartidos.'],
    noRequests: ['No pending requests.','Aucune demande en attente.','Nessuna richiesta in attesa.','Keine offenen Anfragen.','No hay solicitudes pendientes.'],
    request: ['Request a reservation','Demander une réservation','Richiedi una prenotazione','Reservierung anfragen','Solicitar una reserva'],
    pending: ['Requests','Demandes','Richieste','Anfragen','Solicitudes'],
    requested: ['Awaiting confirmation','À confirmer','Da confermare','Bestätigung ausstehend','Por confirmar'],
    accepted: ['Accepted','Acceptée','Accettata','Angenommen','Aceptada'],
    declined: ['Declined','Déclinée','Rifiutata','Abgelehnt','Rechazada'],
    booked: ['Recorded reservation','Réservation enregistrée','Prenotazione registrata','Erfasste Reservierung','Reserva registrada'],
    dog: ['Dog','Chien','Cane','Hund','Perro'],
    service: ['Service','Service','Servizio','Angebot','Servicio'],
    start: ['Start','Début','Inizio','Beginn','Inicio'],
    end: ['End','Fin','Fine','Ende','Fin'],
    note: ['Message (optional)','Message (facultatif)','Messaggio (facoltativo)','Nachricht (optional)','Mensaje (opcional)'],
    send: ['Send request','Envoyer la demande','Invia la richiesta','Anfrage senden','Enviar solicitud'],
    saveError: ['Not saved. Check the fields and connection, or reload if the account changed. Your draft is kept here.','Non enregistré. Vérifiez les champs et la connexion, ou rechargez si le compte a changé. Votre brouillon reste ici.','Non salvato. Controlla i campi e la connessione, o ricarica se l’account è cambiato. La bozza resta qui.','Nicht gespeichert. Prüfe Felder und Verbindung oder lade nach einer Kontoänderung neu. Der Entwurf bleibt hier.','No guardado. Revisa los campos y la conexión o recarga si cambió la cuenta. El borrador se conserva aquí.'],
    datesError: ['Choose valid dates (1 to 366 service days). An overnight stay ends after its start date.','Choisissez des dates valides (1 à 366 jours de service). Une nuit se termine après sa date de début.','Scegli date valide (da 1 a 366 giorni). Una notte termina dopo la data di inizio.','Wähle gültige Daten (1 bis 366 Betreuungstage). Eine Übernachtung endet nach dem Anfangsdatum.','Elige fechas válidas (de 1 a 366 días). Una noche termina después de la fecha de inicio.'],
    accept: ['Accept','Accepter','Accetta','Annehmen','Aceptar'],
    decline: ['Decline','Décliner','Rifiuta','Ablehnen','Rechazar'],
    plan: ['Open planning','Ouvrir le planning','Apri il calendario','Planung öffnen','Abrir el calendario'],
    next: ['Next reservation','Prochaine réservation','Prossima prenotazione','Nächste Reservierung','Próxima reserva'],
    quick: ['For the rest of the day','Pour la suite de la journée','Per il resto della giornata','Für den weiteren Tag','Para el resto del día'],
    shared: ['Share with the client','Partager au client','Condividi con il cliente','Mit dem Kunden teilen','Compartir con el cliente'],
    update: ['News for the client','Nouvelles pour le client','Novità per il cliente','Neuigkeiten für den Kunden','Novedades para el cliente'],
    message: ['Message','Message','Messaggio','Nachricht','Mensaje'],
    publish: ['Share this update','Partager ces nouvelles','Condividi le novità','Neuigkeiten teilen','Compartir novedades'],
    clientFiles: ['Client documents','Documents pour le client','Documenti per il cliente','Kundendokumente','Documentos para el cliente'],
    privateBoundary: ['Only add information intended for this client. Internal notes, health records and accounting originals stay in the private tools.','Ajoutez uniquement les informations destinées à ce client. Les notes internes, dossiers de santé et originaux comptables restent dans les outils privés.','Aggiungi solo informazioni destinate a questo cliente. Note interne, dati sanitari e originali contabili restano negli strumenti privati.','Füge nur Informationen für diesen Kunden hinzu. Interne Notizen, Gesundheitsakten und Buchhaltungsoriginale bleiben in den privaten Werkzeugen.','Añade solo información destinada a este cliente. Las notas internas, historiales de salud y originales contables permanecen en las herramientas privadas.'],
    label: ['Document title','Titre du document','Titolo del documento','Dokumenttitel','Título del documento'],
    file: ['File','Fichier','File','Datei','Archivo'],
    upload: ['Share document','Partager le document','Condividi il documento','Dokument teilen','Compartir documento'],
    members: ['Account access','Accès aux comptes','Accesso agli account','Kontozugänge','Acceso a las cuentas'],
    client: ['Client','Client','Cliente','Kunde','Cliente'],
    carer: ['Trusted carer','Dog-sitter de confiance','Dog-sitter di fiducia','Vertrauensperson','Dog-sitter de confianza'],
    role: ['Access','Accès','Accesso','Zugang','Acceso'],
    email: ['Email','E-mail','E-mail','E-Mail','Correo electrónico'],
    family: ['Recorded client','Client enregistré','Cliente registrato','Erfasster Kunde','Cliente registrado'],
    grant: ['Prepare access','Préparer l’accès','Prepara l’accesso','Zugang vorbereiten','Preparar acceso'],
    revoke: ['Revoke access','Retirer l’accès','Revoca l’accesso','Zugang entziehen','Retirar acceso'],
    accessNotice: ['Access is linked to an existing client and their dogs. No email is sent.','L’accès est lié à un client enregistré et à ses chiens. Aucun e-mail n’est envoyé.','L’accesso è collegato a un cliente registrato e ai suoi cani. Nessuna e-mail viene inviata.','Der Zugang wird einem erfassten Kunden und seinen Hunden zugeordnet. Es wird keine E-Mail versendet.','El acceso se vincula a un cliente registrado y sus perros. No se envía ningún correo.'],
    saved: ['Saved','Enregistré','Salvato','Gespeichert','Guardado'],
    open: ['Open','Consulter','Apri','Öffnen','Consultar'],
    close: ['Close','Fermer','Chiudi','Schließen','Cerrar'],
    detailDay: ['Day care while you are away. Share your dates and your dog’s habits with Adine-Sophie.','Une garde pendant votre journée d’absence. Précisez vos dates et les habitudes de votre chien à Adine-Sophie.','Custodia durante la tua assenza diurna. Indica le date e le abitudini del cane ad Adine-Sophie.','Betreuung während deiner Abwesenheit am Tag. Teile Adine-Sophie die Daten und Gewohnheiten deines Hundes mit.','Guardería durante tu ausencia de día. Indica tus fechas y las costumbres de tu perro a Adine-Sophie.'],
    detailNight: ['An overnight stay to discuss with Adine-Sophie. Specify arrival and departure dates and your dog’s habits.','Un accueil pour la nuit à convenir avec Adine-Sophie. Indiquez les dates d’arrivée et de départ, ainsi que les habitudes de votre chien.','Un soggiorno notturno da concordare con Adine-Sophie. Indica arrivo, partenza e abitudini del cane.','Eine Übernachtung nach Absprache mit Adine-Sophie. Gib Ankunft, Abreise und die Gewohnheiten deines Hundes an.','Una estancia nocturna a convenir con Adine-Sophie. Indica llegada, salida y las costumbres de tu perro.'],
    detailWalk: ['A walk for dogs already known to Adine-Sophie. Share your preferred date; arrangements are agreed together.','Une balade pour les chiens déjà accueillis par Adine-Sophie. Indiquez la date souhaitée ; les modalités se conviennent ensemble.','Una passeggiata per cani già accolti da Adine-Sophie. Indica la data desiderata; i dettagli si concordano insieme.','Ein Spaziergang für Hunde, die Adine-Sophie bereits betreut. Gib deinen Wunschtermin an; die Einzelheiten besprecht ihr gemeinsam.','Un paseo para perros ya acogidos por Adine-Sophie. Indica la fecha deseada; los detalles se acuerdan juntos.'],
    priceUnknown: ['Price to be agreed','Tarif à convenir','Tariffa da concordare','Preis nach Vereinbarung','Precio a convenir'],
    totalUnknown: ['Total to be agreed','Total à convenir','Totale da concordare','Gesamtbetrag nach Vereinbarung','Total a convenir'],
    unitDay: ['per day','par journée','al giorno','pro Tag','por día'],
    unitNight: ['per night','par nuit','a notte','pro Nacht','por noche'],
    unitWalk: ['per walk','par balade','a passeggiata','pro Spaziergang','por paseo'],
    quote: ['Quoted total','Total proposé','Totale proposto','Angebotssumme','Total propuesto'],
    extras: ['Options and price','Options et tarif','Opzioni e tariffa','Optionen und Preis','Opciones y precio'],
    extra: ['Add an option','Ajouter une option','Aggiungi un’opzione','Option hinzufügen','Añadir una opción'],
    extraLabel: ['Option name','Nom de l’option','Nome dell’opzione','Name der Option','Nombre de la opción'],
    unitPrice: ['Unit price','Prix unitaire','Prezzo unitario','Einzelpreis','Precio unitario'],
    currency: ['Currency','Devise','Valuta','Währung','Moneda'],
    quantity: ['Quantity','Quantité','Quantità','Anzahl','Cantidad'],
    lineTotal: ['Line total','Total de la ligne','Totale riga','Zeilensumme','Total de línea'],
    reuse: ['Save for reuse','Garder pour une prochaine fois','Salva per riutilizzare','Zur Wiederverwendung speichern','Guardar para reutilizar'],
    savedOptions: ['Saved options','Options enregistrées','Opzioni salvate','Gespeicherte Optionen','Opciones guardadas'],
    customOption: ['New option','Nouvelle option','Nuova opzione','Neue Option','Nueva opción'],
    save: ['Save','Enregistrer','Salva','Speichern','Guardar'],
    remove: ['Remove','Retirer','Rimuovi','Entfernen','Quitar'],
    edit: ['Edit','Modifier','Modifica','Bearbeiten','Editar'],
    confirmPrice: ['Complete the service price','Compléter le tarif du service','Completa la tariffa del servizio','Angebotspreis ergänzen','Completar el precio del servicio'],
    estimateError: ['Total unavailable. Try again before sending.','Total indisponible. Réessayez avant l’envoi.','Totale non disponibile. Riprova prima di inviare.','Gesamtbetrag nicht verfügbar. Versuche es vor dem Senden erneut.','Total no disponible. Vuelve a intentarlo antes de enviar.'],
    legacyInvites: ['Earlier invitation previews · no access granted','Anciens aperçus d’invitation · aucun accès accordé','Anteprime precedenti · nessun accesso concesso','Frühere Einladungsvorschauen · kein Zugang erteilt','Vistas previas anteriores · sin acceso concedido'],
    account: ['Your account','Votre compte','Il tuo account','Dein Konto','Tu cuenta'],
    accessNext: ['They can then request their personal link from My space.','La personne peut ensuite demander son lien personnel depuis Mon espace.','La persona può poi richiedere il link personale da Il mio spazio.','Die Person kann danach ihren persönlichen Link unter Mein Bereich anfordern.','La persona puede solicitar su enlace personal desde Mi espacio.'],
    noFamily: ['Register the family and their dog first.','Enregistrez d’abord la famille et son chien.','Registra prima la famiglia e il cane.','Erfasse zuerst die Familie und ihren Hund.','Registra primero la familia y su perro.'],
    briefNotes: ['notes today','notes aujourd’hui','note oggi','Notizen heute','notas hoy'],
    briefEmpty: ['No dog registered yet.','Aucun chien enregistré pour le moment.','Nessun cane ancora registrato.','Noch kein Hund erfasst.','Aún no hay perros registrados.'],
    briefBookings: ['{count} saved bookings for today.','{count} réservation(s) enregistrée(s) pour aujourd’hui.','{count} prenotazioni registrate per oggi.','{count} gespeicherte Buchungen für heute.','{count} reservas guardadas para hoy.'],
    briefUnavailable: ['Planning is unavailable.','Le planning est indisponible.','Il calendario non è disponibile.','Die Planung ist nicht verfügbar.','La planificación no está disponible.'],
    firstVisit: ['First visit?','Première visite ?','Prima visita?','Zum ersten Mal hier?','¿Primera visita?'],
    firstContact: ['Introduce your dog to Adine-Sophie on Instagram. You can copy this message; it has not been sent.','Présentez votre chien à Adine-Sophie sur Instagram. Vous pouvez copier ce message ; il n’a pas été envoyé.','Presenta il tuo cane ad Adine-Sophie su Instagram. Puoi copiare questo messaggio; non è stato inviato.','Stelle deinen Hund Adine-Sophie auf Instagram vor. Du kannst diese Nachricht kopieren; sie wurde nicht gesendet.','Presenta tu perro a Adine-Sophie en Instagram. Puedes copiar este mensaje; no se ha enviado.'],
    contactDraft: ['Hello Adine-Sophie, I would like to ask about: {service}.','Bonjour Adine-Sophie, je souhaite me renseigner pour : {service}.','Buongiorno Adine-Sophie, vorrei informazioni su: {service}.','Hallo Adine-Sophie, ich interessiere mich für: {service}.','Hola Adine-Sophie, quisiera información sobre: {service}.'],
    copyContact: ['Copy message','Copier le message','Copia il messaggio','Nachricht kopieren','Copiar mensaje'],
    copiedContact: ['Message copied. Send it on Instagram when ready.','Message copié. Envoyez-le sur Instagram quand vous le souhaitez.','Messaggio copiato. Invialo su Instagram quando vuoi.','Nachricht kopiert. Sende sie auf Instagram, wenn du bereit bist.','Mensaje copiado. Envíalo en Instagram cuando quieras.'],
    copyContactFailed: ['Select and copy the message above.','Sélectionnez et copiez le message ci-dessus.','Seleziona e copia il messaggio sopra.','Markiere und kopiere die Nachricht oben.','Selecciona y copia el mensaje de arriba.'],
    linkSent: ['Request received. If your access exists and delivery is available, you will receive a sign-in link. If needed, try again later.','Demande reçue. Si votre accès existe et que l’envoi est disponible, vous recevrez un lien de connexion. Au besoin, réessayez plus tard.','Richiesta ricevuta. Se il tuo accesso esiste e l’invio è disponibile, riceverai un link. Se necessario, riprova più tardi.','Anfrage erhalten. Wenn dein Zugang besteht und der Versand verfügbar ist, erhältst du einen Anmeldelink. Versuche es bei Bedarf später erneut.','Solicitud recibida. Si tu acceso existe y el envío está disponible, recibirás un enlace. Si hace falta, vuelve a intentarlo más tarde.'],
    signInExpired: ['This link has expired or was already used. Request a new link.','Ce lien a expiré ou a déjà été utilisé. Demandez un nouveau lien.','Questo link è scaduto o è già stato usato. Richiedi un nuovo link.','Dieser Link ist abgelaufen oder wurde bereits verwendet. Fordere einen neuen an.','Este enlace ha caducado o ya se ha usado. Solicita otro.'],
    notes: ['Notes','Notes','Note','Notizen','Notas']
  };
  w.PortalCopy = Object.fromEntries(locales.map((locale,i)=>[locale,Object.fromEntries(Object.entries(rows).map(([key,values])=>[key,values[i]]))]));
})(window);
