"""Synthetic phone media generated by installed local tools."""
from pathlib import Path
import shutil
import subprocess


def make_mov(path, hevc=True, duration=0.4):
    encoder = 'libx265' if hevc else 'libx264'
    args = [shutil.which('ffmpeg'), '-hide_banner', '-loglevel', 'error', '-y', '-f', 'lavfi', '-i',
            f'testsrc2=size=96x64:rate=15:duration={duration}', '-f', 'lavfi', '-i', f'sine=frequency=440:duration={duration}',
            '-c:v', encoder, '-threads', '1', '-pix_fmt', 'yuv420p', '-c:a', 'aac', '-metadata', 'comment=private synthetic metadata']
    if hevc:
        args += ['-x265-params', 'pools=none:frame-threads=1:log-level=error', '-tag:v', 'hvc1']
    subprocess.run(args + [str(path)], check=True, stdout=subprocess.DEVNULL, stderr=subprocess.PIPE, timeout=20)
    return Path(path).read_bytes()
